### ISSUE TITLE
File upload completes but dialog is stuck on "finalizing upload"

### ISSUE THREAD

**Issue by prohtex** [owncloud/web#10492]
## Describe the bug
File upload completes but dialog is stuck on "finalizing upload"

## Steps to reproduce
1. Upload directory with large files
2. Leave browser tab in the background

## Expected behavior
Upload completes and file upload dialog is dismissed.

## Actual behavior
Upload completes successfully, but dialogue is stuck on "finalizing upload"

This happens for me in testing on a fresh Ubuntu VM with basic ocis_wopi deployment. Tokens configured as follows:
 IDP_ACCESS_TOKEN_EXPIRATION: 21600
 IDP_ID_TOKEN_EXPIRATION: 21600

Server logs do not contain useful information. JS console:

![Screenshot 2024-02-16 at 2 57 30 AM](https://github.com/owncloud/web/assets/12946938/fbf23e92-51af-42c9-8b3d-bac7e5207ff1)

**Comment by prohtex** [comment]
I'm experiencing this across the board. File uploads with more than one file dragged complete successfully (from what I can tell) but do not trigger the dialog completion. Is this related to the t.successCount error in the console or is there anything else I can troubleshoot?

**Comment by JammingBen** [comment]
> I'm experiencing this across the board. File uploads with more than one file dragged complete successfully (from what I can tell) but do not trigger the dialog completion.

Just to make sure I get it right: the issue only occurs when leaving the browser tab in the background? Or does it happen with any upload that includes 2 or more files?

Also, it doesn't necessarily has to be a folder upload, right? So 2 single files dragged result in the same issue?

> Is this related to the t.successCount error in the console or is there anything else I can troubleshoot?

If the uploaded content looks alright to you, then the `t.successCount` error is probably the issue here. For some reason Web can't find the upload in its local store, so maybe it gets cleaned to soon for some reason. Needs more investigation (and a way to reproduce) though.

**Comment by JammingBen** [comment]
Should be fixed via https://github.com/owncloud/web/pull/11303, coming to v8.0.5. and the rolling release v10.1.0.
