### ISSUE TITLE
Unsynchronized resources can be downloaded

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10622]
```
Version | 5.1.0-prealpha+ee1178dea
-- | --
9.0.0-alpha.2
```

retested on `5.0.0-rc.6+5787e68d9d` -works correct. relevant only for `ocis` master

<br class="Apple-interchange-newline">

Steps: 

- `admin` shares folders `f1` and `f2` to `einstein`
- `admin` shares files `file1.txt` and `file2.txt` to `einstein`
- `einstein` opens shares and disabled sync for `f1` and `file1.txt`

Expect: no button `download`  on unsynchronized resources

Actual: button `download` is available for unsynchronized resouces
we can download unsynchronized folder `f1` - seems backend issue TODO need investigate
we cannot download unsynchronized file - OK

https://github.com/owncloud/ocis/assets/84779829/1c65c031-f129-47b3-b3ea-e9c713ae717f

cc @nabim777

**Comment by JammingBen** [comment]
In the long term, Web should handle unsynchronized resources exactly the same as synchronized resources, meaning the download action is showing rightfully for all of them.

However, we are currently in a phase of transition, and not all of these things work yet. The question is: how do we want to deal with that in Web?

- Keep the download action visible because it will work some day in the future
- Hide it temporarily as it doesn't work reliably at the moment

@kulmann @tbsbdr

**Comment by kulmann** [comment]
> * Hide it temporarily as it doesn't work reliably at the moment

^ this
