### ISSUE TITLE
[a11y] 9.2.4.6 Meaningful headings and labels

### ISSUE THREAD

**Issue by tschiebel** [owncloud/web#10734]
audit: https://infinite.owncloud.com/s/PnaAukHGGsLnrMM

https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-2-4-6-aussagekraeftige-ueberschriften-und-beschriftungen

### Personal

- [ ] There are several "h4" headings in the "Approvals" area, all of which have the same
title "Link". This can be confusing for users. To create a clear and unambiguous
structure, it is recommended that the titles be adapted accordingly,
for example "Link 1", "Link 2", etc.

### Shares

- [ ] See commentary on Personal

### Spaces

- [ ] Members" areas - "See commentary on Personal"

**Comment by pascalwengerter** [comment]
Open to suggestions on how to solve this (esp. for existing shares), since we create the link share with the translated but hardcoded name "Link" in https://github.com/owncloud/web/blob/d1154ee6bb6e9d35064db3d39f484e729e60fd5c/packages/web-pkg/src/composables/actions/files/useFileActionsCreateLink.ts#L115

**Comment by pascalwengerter** [comment]
@tbsbdr assigning you for RE/specification

**Comment by tbsbdr** [comment]
this is meant (screenshot)
thinking aloud how this could be solved:
we once thought about enumerating links (link 1, link 2 etc.) but decided against it, because its misleading if links get deleted  "it says link 4, but where is link 3?". we could add a date time but then it would get really verbose and the ui would get really cluttered. any other ideas?
![screenshot_002552](https://github.com/owncloud/web/assets/26610733/475421ac-7bf5-4809-bcd9-f0f1241a2e09)

**Comment by tbsbdr** [comment]
- SR-only span in h-element with hardcoded creation date
