### ISSUE TITLE
[Web] Research for `long running actions` (~ Web Worker)

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10855]
research ticket for: https://github.com/owncloud/web/issues/7039

- expect outcome: preferred way how to technically tackle https://github.com/owncloud/web/issues/7039
- Timebox: 3 pd

**Comment by JammingBen** [comment]
See the proof of concept and all related information here: https://github.com/owncloud/web/pull/10916

It feels pretty stable to me, however, I'd recommend to start using it in small incrementions. First we should think about where exactly we want to use this functionality. Looking at https://github.com/owncloud/web/issues/7039, the following 3 are probably good candidates:

* copy
* move
* delete

Then there are 2 more scenarios to think of: uploading and token refresh.

Uploading is not necessary IMO. Yes, it happens in the main thread, but it's already a non-blocking async operation and the user can navigate freely within the application. Also, I don't think we can simply introduce web workers in Uppy.

Token refresh is a bit more complicated. I'm gonna start with saying that I have absolutely no idea if and how we could introduce web workers here, especially since a big chunk of the functionality is located in the oidc lib we're using (btw this is a known issue: https://github.com/authts/oidc-client-ts/issues/954). I'd handle this topic completely separate to be honest, starting with optimizing our token refresh process. It currently re-loads hundreds of assets which results in an error when the network connection is slow. Maybe something similar happens when the browser tab is being throttled? Then we could try doing the token renewal earlier than 10 seconds before expiry, at least if the the token lifespan is > 5 minutes.

**Comment by JammingBen** [comment]
Update to this statement:

> Token refresh is a bit more complicated. I'm gonna start with saying that I have absolutely no idea if and how we could introduce web workers here, especially since a big chunk of the functionality is located in the oidc lib we're using (btw this is a known issue: https://github.com/authts/oidc-client-ts/issues/954). I'd handle this topic completely separate to be honest, starting with optimizing our token refresh process. It currently re-loads hundreds of assets which results in an error when the network connection is slow. Maybe something similar happens when the browser tab is being throttled? Then we could try doing the token renewal earlier than 10 seconds before expiry, at least if the the token lifespan is > 5 minutes.

@kulmann and I did a brainstorming yesterday and found a promising approach. The idea is to just put the timer in a worker, but keep the actual token renewal in the main thread. I'm currently implementing this approach.

For the other operations (copy, move, retry) I'm going to create separate stories so we can tackle them in the next sprint(s).

Since the research part is done and documented here (and in https://github.com/owncloud/web/pull/10916), I'm closing this issue.
