### ISSUE TITLE
Search is available but doesn't work for authenticated user on the public link page

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#10915]
`Version | 5.1.0-prealpha+0ac03d8a8`
`web 9.0.0-alpha.5`

Steps: 
- create folders `f1`
- create link to the folder `f1`
- login in as marie and open link

Actual: 
- Search is not available for public but what should we do if authenticated user? show or not search line? 
- Search doesn't work - 401 Error
<img width="1422" alt="Screenshot 2024-05-16 at 08 16 22" src="https://github.com/owncloud/web/assets/84779829/4e7cda19-078f-4706-938b-7cea96e89a67">

Expected: ? @kulmann maybe you have idea, what should we expect here?

**Comment by kulmann** [comment]
Nice finding! I'd expect that the search input is visible ( ✅ ) and that it works ( ❌ ) as this is an authenticated context. IMO the fact that the view being displayed belongs to a public link is not relevant for the rest of the screen layout (search, app menu, user menu, left sidebar nav).

**Comment by ScharfViktor** [comment]
> I'd expect that the search input is visible ( ✅ ) and that it works ( ❌ ) as this is an authenticated context

yeah, search should work, thank you 👍 
but the search result never gets to Marie the result which related to the public link 
<img width="2272" alt="Screenshot 2024-05-16 at 09 25 08" src="https://github.com/owncloud/web/assets/84779829/99cb695a-72c3-4bfd-b4b0-90b2883b295a">


this can be confusing to the user. Maybe there's some way we can let the user know about it.

**Comment by AlexAndBear** [comment]
I am currently on master branch and admin shared a link. I login as Alex and open the public link from admin as soon I enter the password, I see the content and the search. I can hit the search and I will be able to find results.

Am I getting something wrong here, because it's not reproducible for me...

![image](https://github.com/owncloud/web/assets/26169327/57604481-da2b-483e-a7fe-8f2b137d4075)

**Comment by ScharfViktor** [comment]
> Am I getting something wrong here, because it's not reproducible for me...

I tied reproduce again. I can reproduce.

**Comment by AlexAndBear** [comment]
Can you check on web master with latest ocis ? it works for me

**Comment by AlexAndBear** [comment]
We found the issue, this is happening because we are sending the basic auth header instead of the bearer token while doing the dav report request. 

@ScharfViktor suggested disabling the search entirely when we are in a public link (context), because it will eventually be confusing to the user, that they can't search in the link but the personal space and other places

any opinion @kulmann @tbsbdr  ?

**Comment by kulmann** [comment]
Good finding! No hard feelings. Fine by me to disable the search in that case 👍

**Comment by AlexAndBear** [comment]
I take over and remove it in this context as I think @ScharfViktor s 
considering is valid
