### ISSUE TITLE
Feature request: List only enabled spaces by default in web app

### ISSUE THREAD

**Issue by fpauser** [owncloud/web#11001]
When dealing with lots of spaces it would be really helpful, to only list enabled spaces by default.
Disabled spaces should be hidden by default, maybe by providing a toggle filter next to the spaces search:

```
------------------------------------------------------------------------------------------
                                           [  ] Show disabled spaces (123)      [ search ] 
------------------------------------------------------------------------------------------
```

**Comment by kulmann** [comment]
I like the idea, thanks for the input 👍 Let's do this!

For whoever works on this:

# Description

## User Stories

* > As a user with manager-access to lots of spaces I'd like to have a clean spaces list for my daily work, so that I have the important spaces at a glance. I still want to be able to find disabled spaces though.

## Value
Efficiently work with spaces over a long period of time.

## Acceptance Criteria
- Add a boolean filter (like the `Title only` filter on the search result page), wording `Enabled only`
- A click on the filter toggles the state.
- The filter is enabled (= `true`) by default
- For a consistent UX the filter is aligned to the left on the same row as the search input field above the spaces list
- If the filter is enabled (= default): only show enabled spaces / filter out the disabled spaces from the listing
- If the filter is disabled: show enabled and disabled spaces

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by kulmann** [comment]
Implemented in https://github.com/owncloud/web/issues/11001
Will be part of our next rolling release / sprint increment after sprint end on 14th of June. Next production release will be in autumn this year.
