### ISSUE TITLE
OCM. failure when navigating to the /ocm/invitations page

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11153]
precondition: 

- run two ocis instances `ocis-server` and `federation-ocis-server` see here https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm

Steps: 
- open https://federation-ocis-server:10200
- click by app switcher and click by ScienceMesh
- reload page

Actual: this page isn't working 401 Unauthorized

https://github.com/owncloud/web/assets/84779829/91325f77-d0c8-46b5-b1e7-94cc0e639728

**Comment by kulmann** [comment]
This happens because the app route starts with `/ocm` and all `/ocm` http requests are being routed to the http part of the `ocm` service, see https://github.com/owncloud/ocis/blob/ce199d56ab83d7aedc44f9c74439a7b2e60464af/services/proxy/pkg/config/defaults/defaultconfig.go#L169

Easiest would be to come up with a different web app name.
