### ISSUE TITLE
[test-only] Collaborative Editing on OCM

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#11680]
we should have e2e test for collaborative editing one document between two ocis instances

**Comment by ScharfViktor** [comment]
@amrita-shrestha is currently working on https://github.com/owncloud/web/pull/11838 and https://github.com/owncloud/web/pull/11823
we question the possibility of two ocm users editing a document together. @kulmann is it possible/needed ?

cc @saw-jan

**Comment by amrita-shrestha** [comment]
in ocis work - https://github.com/owncloud/web/pull/11838

**Comment by kulmann** [comment]
> @amrita-shrestha is currently working on #11838 and #11823 we question the possibility of two ocm users editing a document together. @kulmann is it possible/needed ?
> 
> cc @saw-jan

With the current implementation it's not possible so you don't need to add a test for this.

The original feature set of OCM includes a remote editing file action: remote editor gets opened with the OCM token. We disabled that feature in oCIS indefinitely because it's a security nightmare. The OCM token can't be revoked manually so if the link gets sent to someone access to the document is shared without the possibility to revoke it. This can happen via access log sniffing or by a human sending the editor link to someone else.

**Comment by micbar** [comment]
yes please.
