### ISSUE TITLE
Allow creating spaces in admin settings

### ISSUE THREAD

**Issue by butonic** [owncloud/web#11771]
Currently, spaces can be disabled and deleted in two ways:
1. via the files app
2. via the admin settings (batch mode)

New spaces can only be created in the files app.

What is the rationale behind this? Why do we have two places ways to do the same thing? Why can we not create spaces in the admin settings?

Can we merge the batch management into the files app? Or should we add support for creating spaces to the admin settings as well?

In the future I think admins may want to decide which storage provider should host a new space ... but even that might be possible to do in the files app...

**Comment by AlexAndBear** [comment]
Spawning @tbsbdr  and @kulmann

**Comment by kulmann** [comment]
Because we only had time for the most important feature set back then. I don't see a reason forbidding creating spaces in the admin settings app. Actually on the contrary, it makes perfect sense. We just never thought about it anymore when the MVP was done.

Happy to have it. Files app should always be the most simple version of the process. Having more complexity in the admin settings app is fine.
