### ISSUE TITLE
[QA] misleading error message when private link is not resolvable

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#12009]
## Describe the bug
![image](https://github.com/user-attachments/assets/89b2319f-8ac1-4c4b-b8d3-03af2fec07fe)

## Steps to reproduce
1. User alice creates a private link to some of her folders (not shared with anybody) and discloses the link to bob.
2. User bob tries to access the link. An error appears that claims, that it is shared, but needs "syncing". This is wrong. BAD
3. Same error appears when the link is malformed.

## Expected behavior
A clear and concise error message should say: 
- you don't have access. 
- the link is malformed.
- ...

## Actual behavior
The user is mislead to actions that don't help.

**Comment by JammingBen** [comment]
I agree that the error message doesn't make sense, especially since enabling the sync doesn't affect accessing a share anymore. However, we can't really tell why such a link is not working. Maybe the user doesn't have access to the requested resource, or maybe the resource doesn't even exist - we just can't know that. Hence I'd go for a generic wording.
