### ISSUE TITLE
Focus after closing modal

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1646]
## Description
As the user closes the modal focus is not being sent back to the button triggering said modal (but to someplace else)

**Comment by marcus-herrmann** [comment]
# Problem (abstract)
This issue is, like #1647, also a matter of focus management and traceability of focus for the user. Although not a WCAG success criteria validation, this [best practise](https://simplyaccessible.com/article/modal-focus/) is well-established and well-tested

# Solution (abstract)
Storing a reference of the triggering button in memory. In the close event handler, focus it.

# Solution in phoenix
(wip)

**Comment by pascalwengerter** [comment]
@fschade has introduced a focus recording in https://github.com/owncloud/web/pull/4993 which we've implemented for a bunch of use cases already. Will do a final check before handover to the a11y auditor next week but closing this for now
