### ISSUE TITLE
Password dialog for public link is triggered after redirection from old web UI

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1693]
### Steps to reproduce
1. Open phoenix.owncloud.com
2. Log in to the old web UI
3. Navigate into Phoenix via apps menu
4. Dismiss prompts from browser to login

### Expected behaviour
User stays at authorise page of Phoenix

### Actual behaviour
I'm redirected to password dialog for public link page

### Client configuration
**Browser:** https://www.whatismybrowser.com/w/HA55HX7

**Operating system:** Mac OS Mojave

**Comment by DeepDiver1975** [comment]
I know what this is .....

**Comment by DeepDiver1975** [comment]
this is the code in question - https://github.com/owncloud/phoenix/blob/2d07ad6eb345a10e4ed7e4e11550a37e3bc0bf30/apps/files/src/components/FileList.vue#L134-L140

**Comment by PVince81** [comment]
I also noticed that whenever I reset my Phoenix env, the browser still believes I'm logged in or in the public link page, but shows an error as it's not valid any more, despite the URL not showing anything.

I suspect this is related to whatever is stored in local storage.

Note that when you are on a public link page that has a password, even after password entry, if you refresh the page it asks for the password again. This is probably because the password is not stored in local storage so it prompts for it again, which I think is ok.

**Comment by DeepDiver1975** [comment]
This also happens in cases where the token expires and a PROPFIND is sent which returns with a 401.
https://github.com/owncloud/phoenix/blob/3da3b4e8cbedc427dcf9b42cdefa371d16aefee3/apps/files/src/components/AllFilesList.vue#L124

We might want to think about splitting public files from the 'private files' via url

**Comment by pascalwengerter** [comment]
@LukasHirt could you check if this still happens/has been fixed by all the changes in `web-app-files`? Can't find the respective code deepdiver mentioned above anymore

**Comment by LukasHirt** [comment]
Haven't seen the dialog for a very long time now and the code for public/private files have been split wherever it could have been done.
