### ISSUE TITLE
Translating strings from within the theme and js files

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#1942]
## Description
We have already few strings inside of theme and we are not translating them at all. We need to find a way how to translate them. Not sure if gettext is capable of extracting it. Needs some digging.

**Comment by LukasHirt** [comment]
Seems that we can now at least translate js files directly - https://github.com/Polyconseil/vue-gettext/pull/113

**Comment by pascalwengerter** [comment]
What's tbd to fix this issue?

**Comment by LukasHirt** [comment]
We're already capable of importing gettext into js files https://github.com/owncloud/web/blob/237598bf0c6da0ac111ead14a06c297d54772692/packages/web-app-files/src/store/actions.js#L7 What we need now is to actually make the locale reactive for plain js files - atm it won't respect changes in selected language until a refresh

**Comment by dschmidt** [comment]
Is this issue still relevant? 

We have translations in js, ts and vue files (also with lang=ts). 

I guess if some translation is not reactive is because it is not wrapped in a computed, otherwise it should be afaik. 


What are the acceptance criteria of this ticket? 
I'd argue any occurence is an individual bug and should be tracked/fixed as such. I don't see any value in this ticket (anymore)

**Comment by JanAckermann** [comment]
as @dschmidt mentioned, translations should work, if on some occurences is not, please open dedicated issues
