### ISSUE TITLE
Media viewer preloading

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2052]
The current media viewer implementation is missing image preloading.

When clicking on the icon for going to the next picture, the current picture fades out and I need to wait a few seconds for the new one to load. This is a rather frustrating experience.
The OC 10 media viewer was smoother thanks to preloading.

@felixheidecke

**Comment by kulmann** [comment]
This is a good idea for images. For audio and video formats I'd like to keep the current behaviour of loading the file when playback gets triggered.

**Comment by JanAckermann** [comment]
@kulmann should there be a limitation, like only preload the first 200 images ?

**Comment by dschmidt** [comment]
> @kulmann should there be a limitation, like only preload the first 200 images ?

I'm not @kulmann  :-P but imho: YES YES YES YES YES and YES. Imagine opening a huge phone backup folder with thousands of images hammering the backend with thousands of requests and caching the results in memory, I doubt this gives a better feel of performance than right now 😅 

I would argue instead of loading "the first 200 images" we should rather load the previous and next x pictures when the active file changes (where probably something like 10 is more than enough)

**Comment by kulmann** [comment]
> @kulmann should there be a limitation, like only preload the first 200 images ?

I'd say for the currently shown image only preload the previous 10 and next 10 images (which needs to respect the currently active sorting of the files of course). If you navigate to the next image, preload one more image (the 11th, which now became the 10th).

**Comment by JanAckermann** [comment]
if the next file is a video file should I still try to preload the next image?

**Comment by kulmann** [comment]
> if the next file is a video file should I still try to preload the next image?

I'd say
- only preload the next x files
- only actually preload if the file is an image :trollface: 

=> if the next files are 1. image, 2. video, 3. image, 4. image, 5. audio, 6. image, 7. image
=> preload 1, 3, 4
