### ISSUE TITLE
Login is cumbersome

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2064]
Due to the oauth handshake process, the login process goes through several steps.
The first time it's ok.

However, now every time I want to login I need to authorize the app again.
And when I want to switch the user, I need to click "Authorize" first and then click "Switch user" on the second page.

We should look into ways to simplify the flow.

Maybe if we already had a logged in user we could directly redirect to the OC server's authorize page where the user can be switched ? Or have a dialog like Google that shows the last logged in user (or the one currently logged in on the server, if we can know) with a button "Log in as XYZ" and another one "Login as someone else".

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
Regarding the Switch user screen.: As long as we so Not Support the logout Mechanism(which is Part of openidconnect) we need to keep this screen because this is the only was to really loggout

**Comment by PVince81** [comment]
Nice, here's the PKCE ticket: https://github.com/owncloud/phoenix/issues/511

**Comment by PVince81** [comment]
@pmaier1 @michaelstingl as discussed I'm moving this into M1 scope as it is scary for a first impression of Phoenix

**Comment by PVince81** [comment]
Effort for the PKCE was estimated to 5d

**Comment by kulmann** [comment]
With https://github.com/owncloud/web/pull/7072 being merged we finally switch over to using PKCE in web as well. Regarding the user switch and already on web current master, without the mentioned PR:
- the logout in web now calls the oc10 logout url after removing the user from the browser session. i.e. logout actually logs out of oc10 entirely
- web can be defined as trusted client, so that the authorize page doesn't appear anymore at all.

Considering this ticket as done if no one speaks up.
