### ISSUE TITLE
[QA] Search icon click should start the search

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2130]
After entering some text in the search field, 
A click on the search icon does nothing. 

Pressing ENTER starts the search.
![image](https://user-images.githubusercontent.com/1108546/66054178-e3d52400-e533-11e9-9a1c-c7c54a55ffcf.png)

Expected behaviour:
The search should start when I hit ENTER or when I click the search icon

**Comment by PVince81** [comment]
I think the search icon is not meant to be clicked, it's just like a label that tells users that this is the search field. If the icon was on the right hand side, I might expect it to be clickable.

Maybe the icon is too bold and need to be brighter to remove the impression that it is clickable.

**Comment by PVince81** [comment]
needs designer input

**Comment by pascalwengerter** [comment]
Outdated since the search field has changed a lot. Search works with OC10, you can try it on web.owncloud.com, the component lives here: https://owncloud.design/#/oC%20Components/OcSearchBar

<img width="835" alt="Screenshot 2021-04-08 at 15 42 27" src="https://user-images.githubusercontent.com/16822008/114046761-078fcd80-9881-11eb-8261-c5a64be436b8.png">
