### ISSUE TITLE
[QA] Missing error description for folder creation (folder already exist)

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2135]
Steps:

* Create a new folder (1)
* Create within folder (1) a new folder (2)
* Permit any user for folder (1) but deactivate the role inheritance (User can't see the folder (2))
* Login with the mentioned user and open folder (1)
* Try to create a new folder by using the same folder name (name of folder (2))

![image](https://user-images.githubusercontent.com/1108546/66059120-cb690780-e53b-11e9-9b1f-cb07ebf724b0.png)

ACTUAL: An error message is displayed. The correct error description (e.g. Folder with the same name already exist) is not
displayed.

EXPECTED: The correct error description (e.g. Folder with the same name already exist) should be displayed.

**Comment by DeepDiver1975** [comment]
The description which is currently displayed is returned by the server - if we want to change this we need to change owncloud/core

**Comment by PVince81** [comment]
Note that if a folder already exists and is present in the list (state), the dialog will already show a proper error without even contacting the server.

This would likely happen if the folder was created by another party or inside a separate tab so that the dialog does not know directly about its existence. So the error message would come from the server.

**Comment by pascalwengerter** [comment]
Closed as fixed, error message is translate-able now
