### ISSUE TITLE
Reword modification time

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2251]
- "modification time" => "modification date"
- check with other solutions to see what wording they use

@wuenschedesign

**Comment by LukasHirt** [comment]
What about using just "Modified"? Since we are using dateFromNow and always get "... ago". Also, what about the design from you @wuenschedesign where we dropped the headers completely? Maybe throw here a picture and we can discuss that as an alternative?

**Comment by DeepDiver1975** [comment]
As discussed in the call - dropping headers can cause confusion - while it might be clear in most cases - especially an unnamed date column is unclear - this could be: modified date, upload date, create date, access date ........ so maybe we drop headers for the obvious columns ... 

Furthermore I could imagine that the headers are necessary from an accessibility point of view ....

**Comment by LukasHirt** [comment]
I see. Thanks for making it clear. I guess accessibility wouldn't be such a problem since we can add there then some explanation like "Modified 2 days ago".

But I'd still actually say it could be a nice improvement and help us with "Phoenix looks like it was made in 2000". So as you wrote, maybe some obvious columns. I'd say e. g. size could be one of them. Also, tags could look nice there.

I played this some time ago as well and had this back then.
![image](https://user-images.githubusercontent.com/25989331/66929049-ac39a200-f032-11e9-83eb-ea108825a7ed.png)

**Comment by LukasHirt** [comment]
Dropbox went also the way without headers. Just add before the date "Added". Personally I like that!

![image](https://user-images.githubusercontent.com/25989331/66929562-8a8cea80-f033-11e9-99fc-2424fe90972f.png)

**Comment by dragotin** [comment]
I think this is not longer valid. Pls reopen in case it is.
