### ISSUE TITLE
Private links to files should not show the folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/web#2281]
We currently "misuse" the folder view (with added scrollto and highlight) as a file link. 

If I want to point to a specific PDF, I don't want the user to be distracted by the nice photos that happen to be near that PDF.

A direct view/download landing page per file would be the better solution, IMHO.

**Comment by kulmann** [comment]
In my opinion both behaviours (navigating into the folder in the files app or triggering the default action for the file) are not ideal and for any of the two solutions we'd have someone who has the impression that it's wrong.

I'm closing the issue now, since the current solution is ok and gives the opportunity to let the user choose the file action they want.
