### ISSUE TITLE
Support for more dynamic configuration and app loading

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#2544]
### Current situation:
- config.json is hard-coded into the Phoenix server
- app list hard-coded into config.json and assumes that it is hosted in the same domain
- app info JS is hard-coded into the app bundles
- app bundle is loaded by convention under the URL "apps/$app/$app.bundle.js"
- ability to load external apps using "external_apps" that would load the config from a remote URL

### Changes
- [ ] make it possible to load the configuration and the list of apps (app URLs) from a separate endpoint. Might require having a "bootstrap" config.json that only points to the URL that contains the actual dynamic config. Unless the OCIS service that serves Phoenix can also override that route.

- [ ] app list must be a list of URLs from which to load the "appinfo.json"
- [ ] Provide appinfo.json for apps to be located at the domain where the app is deployed
- [ ] appinfo.json contains app config
- [ ] optionally: another endpoint specific for the app's config.json ? or by convention ?
- general rule: if a relative URL is given in any config, always load it relative to the domain on which it was hosted (ex: app URLs)

@LukasHirt @DeepDiver1975 thoughts ?

**Comment by PVince81** [comment]
ok seems I missed that we already had "external_apps" in the config.json.
maybe we should unify that to have it also for the local apps ?

**Comment by DeepDiver1975** [comment]
The more different additional json files we load the long the bootstrapping process will take.

Since config parameters don't change that often is is acceptable from my pov to edit the config file on the server. With respect to the static loading - via web server routing this file could also be loaded from a server and data can be compiled at runtime. (if ever needed).

Regarding app loading - if we follow the multi-url SPA concept each app will live on it's own and will read it's own config file anyhow.
Shared config will then be the list of applications for the application switcher/menu.

See #2573

**Comment by PVince81** [comment]
Feels like this is likely obsolete: with the current config.json and its ability to be a dynamic endpoint, I guess all this is already covered.

**Comment by LukasHirt** [comment]
We still provide a static config.json. In ocis-web, it is a generated config.
