### ISSUE TITLE
Cache for avatars

### ISSUE THREAD

**Issue by PVince81** [owncloud/web#3098]
Instead of loading the avatars every time, cache it at least in the scope of the current page until a page reload.

What currently happens is that when there's a list of repeated avatars (ex: collaborators in the "shared with others" list), each avatar is loading again on its own, with different timings. So they don't appear at the same time.

**Comment by pascalwengerter** [comment]
@fschade to what extent did #5073 mitigate this issue?

**Comment by fschade** [comment]
> @fschade to what extent did #5073 mitigate this issue?

no, at the moment we only cache the url // presigned-url.

**Comment by kulmann** [comment]
The browser cache can only kick in for the already known URLs. Which is for max. 60 seconds now. Since presigned URLs get invalidated pretty quick we cannot build a reasonable cache at the moment. For a single page load it is improved though, since we re-use the same presigned URL by userId. As a result, if one and the same avatar is on the current page 5 times, we only load it once and use it 4 times from the cache (native browser caching).
