### ISSUE TITLE
Do not display folders first if sorting by name is selected

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3618]
If sorting by name is selected, we also assume that the folders should be displayed first. What would you say about differentiating between sorting by name and by kind? This is e.g. how finder in macOS does it.

IMHO it makes sense that if I sort by name and have a file starting with "a" it would appear before folder starting with "z". But not to break this for users that prefer it that way, I think the sorting by kind would be good enough

**Comment by kulmann** [comment]
IMO having all folders first and then files, or mix folders and files, is a perfect candidate for a setting (user preference). Because - I think - you would not constantly switch between the two listing behaviours, but only set it once the way you like it and then except the UI to respect that choice.

**Comment by kulmann** [comment]
Never heard anyone complain about our current way of sorting the file list since this ticket as been created. Closing as not planned. Can be reopened if the need arises.
