### ISSUE TITLE
xml files don't have a priview/icon

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#3839]
### Steps to reproduce
1. upload a .xml file

### Expected behaviour
some kind of icon like other files

### Actual behaviour
Tell us what happens instead
![image](https://user-images.githubusercontent.com/2425577/88623219-36d02700-d0c4-11ea-9ad9-f1f7f51acd19.png)

**Comment by fschade** [comment]
needs to be discussed if this makes sense, at the moment we support thumbnails for txt files, so in my opinion nothing speaks against it. cc @kulmann

**Comment by kulmann** [comment]
The issue here was that xml files had neither (not a preview and not a generic icon for the file type). Has been fixed with https://github.com/owncloud/web/pull/4357

See screenshot:
<img width="210" alt="Screenshot 2021-06-15 at 14 12 46" src="https://user-images.githubusercontent.com/3532843/122050484-c9b0a780-cde3-11eb-97a7-a1212785a661.png">

If xml files should have previews is a decision for the thumbnail service in ocis, not a web issue.
