### ISSUE TITLE
UX: Collaborators action naming

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3907]
When clicking "collaborators" I also get other file information such as versions and links, maybe this should be called something more generic?

To access versions I have to go through the Sharing icons, this is not intuitive

**Comment by PVince81** [comment]
AFAIK the action is just a shortcut to the sidebar tab with the same name

**Comment by LukasHirt** [comment]
The sidebar can be also opened by clicking on the row itself. As soon as we have a Details tab we can also add an item for it in the actions dropdown.

**Comment by diocas** [comment]
@labkode I'm tempted to close this  as no longer seems relevant ti the current version (although it hasn't changed much).

**Comment by kulmann** [comment]
I'm also for closing this one. The right sidebar has an accordion now, so upon navigating into that right sidebar we clarify the active context by allowing only one accordion item to be open. With that this issue here should be done.

More context though: We don't have a context menu at the moment and the naming is not `Collaborator` anymore but `People` instead. There are two ways of opening the right sidebar. We have plans for developing a `Details` accordion item in the current sprint (10.-28.05.2021) and have that as the first visible accordion item by default on opening the right sidebar. There are plans for developing a new context menu in the next sprint (31.05.-18.06.2021). That context menu will have certain actions for opening the right sidebar with a certain accordion item being open.

**Comment by labkode** [comment]
Yeah we can close this one
