### ISSUE TITLE
UX:  No option to share a folder when inside it

### ISSUE THREAD

**Issue by labkode** [owncloud/web#3919]

**Comment by PVince81** [comment]
related https://github.com/owncloud/phoenix/issues/2061

**Comment by pascalwengerter** [comment]
@tbsbdr can we discuss this in the design initiative?

**Comment by kulmann** [comment]
We already have a concept for this, and a story, but somehow it doesn't appear in github. Issue in Jira is WEB-29. The idea is to give the option to the user to open the right sidebar without having a file/folder selected. With that sharing becomes available for the current folder. As of now the Issue is planned for the next sprint, to be released end of June.

**Comment by kulmann** [comment]
Will be solved when https://github.com/owncloud/web/issues/5165 is implemented. Still planned for end of June.

**Comment by kulmann** [comment]
Will be fixed when https://github.com/owncloud/web/pull/5678 is merged
