### ISSUE TITLE
Do not show parent folders in favorites

### ISSUE THREAD

**Issue by frankaellen** [owncloud/web#4608]
Hey, 

could we show only the folder name in the Favorites list and remove the ".../.../..." before? From a user perspective it feels a bit crowded and unnecessary information in that weight/size. See screenshot attached :)
Maybe we have to think about a component / design item that displays breadcrumbs within one list item instead. 

All the best, 
Franka

<img width="1440" alt="Screenshot 2021-01-14 at 10 05 16" src="https://user-images.githubusercontent.com/4892549/104569026-146d9e00-5651-11eb-9b10-2a888ae6deff.png">

**Comment by LukasHirt** [comment]
Improvements from the current rework of files table:

![Screenshot 2021-01-14 at 15 35 01](https://user-images.githubusercontent.com/25989331/104604849-1568f480-567e-11eb-8fe4-33194514c900.png)

**Comment by tbsbdr** [comment]
## What is the path good for?
**Prevent name collision:** I think the path is useful to distinguish favored files with the same name and it gives some context (=orientation - "where is the file?").

My guess is, that in most usecases users favor mainly folders and only in some cases files (90% - 10% or so..).

Heuristics:
- Win 11 can only favorize "pin" only folders, no files
- MacOS can only favorize folders, no files
- found almost no requests in help-forums where users ask how to pin/favorize files

If it is true, that favoring files is a quite rare usecase, name collision would also be rare. (besides: name collision could also happen for folders, but is not prevented by design)

**orientation:** The tooltip displays the path, this should be sufficient for orientation.

## Should we remove the path / parent folder?
--> **Yes**, I agree with Franka. I think we should on the one hand drop the path to gain more clarity in the files list on the other hand.  

## Enhancement: How to provide orientation for "isolated" files?
This task must also be solved for a proper search result list. As soon as we have a proper solution for the search results list, we can adapt "orientation" -pattern from there to the favorites.

**Comment by tbsbdr** [comment]
solved by #5953
