### ISSUE TITLE
Unclear contribution situation

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#4666]
### Steps to reproduce
1. Be interested in contributing
2. Go to [contribution guidelines](https://github.com/owncloud/web/blob/master/.github/CONTRIBUTING.md)

### Expected behaviour
Leave with a clear understanding how contribution works for this repository / owncloud repositories

### Actual behaviour
1. In the `web` repository, there's a broken link to a [contribution agreement](https://owncloud.org/about/contributor-agreement/)
2. In the legacy `core` repository, there's a link to an existing [contribution agreement](https://owncloud.com/contribute/join-the-development/contributor-agreement/)
3. In the new `ocis` repository, there's no notice of such an agreement at all

### Server configuration
Not applicable

### Client configuration
**Browser:** All
**Operating system:** All

### Logs
Not applicable

#### ownCloud log (data/owncloud.log)
Not applicable

#### Browser log
Not applicable

**Comment by kulmann** [comment]
For oCIS the contribution guideline is a simple `Fork -> Patch -> Push -> Pull Request` as stated in the readme: https://github.com/owncloud/ocis#contributing
We don't need a signed contribution agreement on PRs to oCIS because we're using `Apache-2.0` as a license there.

For the web repo I made a PR, which you already know. :-)
