### ISSUE TITLE
CI failing in master

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#4741]
See PR https://github.com/owncloud/web/pull/4739 which demonstrates the problem.
https://drone.owncloud.com/owncloud/web/13163/5/20

The UI test scenarios do not seem to get to login when running with an oC10 backend.

**Comment by dpakach** [comment]
CI should be fixed by https://github.com/owncloud/web/pull/4740 for the time being. This PR changes the SUT configuration from OpenID connect to oauth2, we still need to investigate why the openid connect setup started to fail, but since we are using very old version ocis-glauth (as current version doens't support owncloud backend datastore), it may be anything.
