### ISSUE TITLE
Always redirect requests from the UI to homeFolder

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#4823]
With the `homeFolder` option, the user homes can be configured to arbitrary paths instead of the default root. But the change is not applicable across the UI.
- Clicking on the home icon in the 'All files' tab should redirect to `homeFolder` instead of root.
- Endpoints for the files from the 'Shared with me' and ''Shared with others' should also have the `homeFolder` prefix.

**Comment by kulmann** [comment]
The home icon in the breadcrumbs is misleading. In fact it represents the root, not the home. Otherwise there would be no other way to navigate up to the root. If there is no `homeFolder` configured, home is basically the same as root (home  = root for the authenticated user). We'll need a better icon anyway when we implement spaces/project folders in the web ui and probably continue to use the breadcrumbs. What do you think?

As for your second point, that's of course correct and needs to be fixed. Do you want to try a PR? :-)

**Comment by ishank011** [comment]
@kulmann it makes sense for the breadcrumbs part, I think we can just let it be for now. For the second one, I'll ask people getting started with the project to take a look.

**Comment by ishank011** [comment]
@kulmann please take this up when you have the chance. We have quite a few things going on so it'll be difficult to spare time to look into this

**Comment by kulmann** [comment]
alright 👍

**Comment by kulmann** [comment]
@ishank011 could you confirm that this is what you need? https://github.com/owncloud/web/pull/4926

To be honest I don't get how in your setup the user has access to the storage root but shares still live in the users homeFolder path. Struggling to write meaningful tests for it.

**Comment by kulmann** [comment]
Pinging @LukasHirt @pascalwengerter @fschade here so that they get updated with more information as well.

**Comment by pascalwengerter** [comment]
@ishank011 could you update us on whether this has been resolved by https://github.com/cs3org/reva/pull/1605?

**Comment by ishank011** [comment]
We can close this since it's being tracked in reva itself
