### ISSUE TITLE
Duplicate requests when homeFolder is enabled

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#4860]
For a homeFolder value of `/eos/user/{{substr 0 1 .Id}}/{{.Id}}`, we see repeated requests when visiting the web app for the first time
```
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser%2Fi&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser%2Fi&shared_with_me=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser%2Fi&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser%2Fi&shared_with_me=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser&shared_with_me=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos%2Fuser&shared_with_me=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos&shared_with_me=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos&reshares=true
/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Feos&shared_with_me=true
```

While we shouldn't be sending the same requests again and again, I don't understand why we need to send these for the parent directories in the first place.

**Comment by labkode** [comment]
@kulmann any news on this?  Performance is impacted by such number of requests

**Comment by kulmann** [comment]
The bug was unrelated to the homeFolder feature.

Context: we're loading the shares of the current folder and all parent folders to be able to display share indicators on the listed resources (because it might be shared via a parent folder). This is cached for the current path. If you leave the current path (i.e. go to a child of the path or to a sibling) the cache gets cleared. If you traverse to parents, shares are already cached.

Fix is here: https://github.com/owncloud/web/pull/4918
