### ISSUE TITLE
enabled screenshots and failing VRT tests seem not to work together

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#4869]
something went wrong in this build
https://drone.owncloud.com/owncloud/web/13882/13/14

some tests failed and uploaded screenshots and also the VRT test failed, but there is no github comment about the vrt failure (only ocis no oc10)
see https://github.com/owncloud/web/pull/4862#issuecomment-808032357

**Comment by individual-it** [comment]
here https://github.com/owncloud/web/pull/4985#issuecomment-823043537 it seem to have uploaded the VRT failures but also screenshots of other expected failures
![image](https://user-images.githubusercontent.com/2425577/115499968-28e4b680-a290-11eb-8be3-ce2ebc312b3c.png)

**Comment by dpakach** [comment]
@individual-it It shows the screenshots for VRT tests and regular tests separately (eg. https://github.com/owncloud/web/pull/5062#issuecomment-831679813)

As for the large number of screenshots showing, I can't think of any way to fix that. when screenshots are enabled all failing tests will produce screenshots. And the screenshots are just named with the timestamp, so not really any way to identify which screenshot is for actual failure. But we can check the drone logs to identify if it's the VRT failing or regular test, if the failure is because of VRT we can ignore the remaining screenshots.

**Comment by individual-it** [comment]
@dpakach could we enable screenshots only for the second run of nightwatch? So the first try would not even produce screenshots?

**Comment by dpakach** [comment]
@individual-it, I found a way for that. We can basically save the screenshot using the selenium API rather than just using the magic config. that way we get to name the screenshot according to the feature file and it would be easier to recognize which screenshot is for which feature

**Comment by dpakach** [comment]
Added the fix for this in https://github.com/owncloud/web/pull/5062
