### ISSUE TITLE
Do not re-authenticate when not needed

### ISSUE THREAD

**Issue by diocas** [owncloud/web#5210]
As far as I understood, you keep the authentication/session information (tokens) in the browser local/session storage, right?
But, if I open a new tab, I go through the auth process again, even if the previous information is still valid. Could we do the re-auth only if there's a need to (i.e expired token)? Or is there any security implications?

I'm thinking about this because it's useful to let users *easily* open new tabs. Wether they want to open a folder separately, or because we open files (in their respective apps) in new tabs, which I think is the best way for apps like collabora.

**Comment by kulmann** [comment]
With https://github.com/owncloud/web/pull/7072 being merged we keep the context state (access token for a user context, public link token and password for a public link context) in the session storage + use it in new tabs, browser reload, etc. The user object doesn't get persisted to the session storage anymore because that logic was overly complex and we didn't want to keep it + obtaining potentially new information on a page reload is helpful. @diocas could you please give feedback if this fixes the issue?

**Comment by diocas** [comment]
Looks awesome!!
