### ISSUE TITLE
[QA] Collaborators appear in a folder that was not shared

### ISSUE THREAD

**Issue by davitol** [owncloud/web#5278]
Tested with
 * ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
 * firefox and Chrome in Mac

### Steps to reproduce

1. user A shares a file with user B
2 . user B accepts the share and file appears
2. User B creates a folder in home path
3. Browse into the folder
4. Create a subfolder

### Expected behavior

Collaborators shown should be only the own user

### Current behavior

It appears 2 collaborators, user A and user B

![collaboratorsFolder](https://user-images.githubusercontent.com/10596560/93185632-f002c300-f73d-11ea-8b55-44c418f89e97.gif)

**Comment by pascalwengerter** [comment]
@davitol @labkode @ishank011 any news/feedback on this one?

**Comment by dschmidt** [comment]
I tried to reproduce this now but I couldn't. Here's what I did (as the report is not very specific about the sharing).

- admin shares file `example-pictures/download.jpeg` with user einstein
- einstein accepts share
- einstein creates folder `foo` in home
- einstein clicks on foo
- einstein creates folder `bar` in `foo`

No sight of any incorrect collaborator.
I tried to create files or folders named download.jpeg and tried again with sharing the example-pictures folder and creating folders named like that in root or subfolders. No way to see collaborators that should not be there.

As this issue is pretty old by now and there was no response to a request for feedback, I'm closing it now.
If you can still reproduce this: please reopen and add information about file and folder names used etc.
