### ISSUE TITLE
Listing shares blocks on WebDAV call for rendering

### ISSUE THREAD

**Issue by labkode** [owncloud/web#5337]
This issue drastically reduces performance.
We're on latest master.

When clicking on:
* Shared with me
* Shared with other
* Shared via link

https://user-images.githubusercontent.com/5175912/122888720-63c3a300-d342-11eb-96bd-17ffbf891e13.mov

There is no reason to send a WebDAV request.

@pascalwengerter @kulmann @fschade @diocas @elizavetaRa 
Please include this fix in https://github.com/owncloud/web/pull/5178

**Comment by fschade** [comment]
@labkode thank you for the hint, we will have a look into the issue

**Comment by labkode** [comment]
I reopen this one as is the same context but a different call, this time to cloud/user.


https://user-images.githubusercontent.com/5175912/122929829-ad74b380-d36b-11eb-9332-aad815a425f2.mov

**Comment by pascalwengerter** [comment]
> I reopen this one as is the same context but a different call, this time to cloud/user.
> ocis_blocks_cloud_user.mov

From what I understand at this point this fetches the user's quota, and since we're not updating it on push from the server we'll have to query it every once in a while so the user can reason about their free space. Might make sense to skip it on the "Shared with others" and "Shared via Link" since there's nothing happening with the quota there, but on "All files", "Shared with me" and "Trashbin" we perhaps need to keep it

**Comment by labkode** [comment]
@pascalwengerter I agree, only need to do it on All files. On Shared with me is also debatable, do shares account on your quota?

**Comment by pascalwengerter** [comment]
> @pascalwengerter I agree, only need to do it on All files and Trashbin. On Shared with me is also debatable, do shares account on your quota?

Sorry @labkode that took a bit longer on my side. From what I gathered shares don't account on your quota, and since the quota isn't even displayed anywhere / not relevant _for now_ I removed it where I could. We will have to come back to that topic once spaces get implemented since quotas _for spaces_ will become relevant then, but that's a topic for another day ;)
