### ISSUE TITLE
delete pending share option is not available for sharee

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5435]
## Describe the bug

Using with `ocis` backend with either storage driver, deleting a pending share option for share is not available

## Steps to reproduce

1. create two users `uu1` and `uu2`
2. upload a file `lorem.txt` using user `uu1`
3. share file `lorem.txt` with user `uu2` using user `uu1`
4. login with `uu2`
5. browse to `shared-with-me` page
6. open actions panel for the last share received i.e `lorem.txt`

## Expected behavior
- delete button to delete the incoming share

## Actual behavior
- delete button pops only after accepting the pending share

## Setup

Please describe how you started the server and provide a list of relevant environment variables.

<details>
<p>

```console
WEB_VERSION=git
BRANCH=master (latest)
OCIS_VERSION=git
BRANCH=master (latest)
STORAGE_FRONTEND_UPLOAD_DISABLE_TUS=false
```

</p>
</details>

**Comment by kulmann** [comment]
Honestly, on the `shared-with-me` page I would not expect any `Delete` button, because I'm looking at shares. I would expect `Accept share` and `Decline share` buttons only. This PR https://github.com/owncloud/web/pull/5374 modifies the behaviour so that the shared with me page only shows a `Decline share` button in the right sidebar, not a `Delete` button anymore.
