### ISSUE TITLE
`calculate-diff` blows up CI time

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5487]
### Steps to reproduce
Check CI on drone.owncloud.com for the web project and see the following

<img width="348" alt="Screenshot 2021-07-08 at 15 29 24" src="https://user-images.githubusercontent.com/16822008/124940008-81ab2c00-e001-11eb-91aa-82f3efbe6f73.png">

### Expected behaviour
`calculate-diff` should run once within the unit tests step and then determine whether the acceptance tests should be run

### Actual behaviour
`calculate-diff` is executed _in every acceptance test step_ and sometimes runs for >20min

**Comment by phil-davis** [comment]
In all the recent drone builds that I have "randomly" looked at, that step takes less than 10 seconds.
drone agents got very slow at pulling docker images and dependencies yesterday. I suspect that 24:50 of the time was "hanging" until the docker image came.

 @pascalwengerter can you give a link to the build?

**Comment by phil-davis** [comment]
Note: in order to decide what tests should or should not be executed, based on the files changed in the PR, we have to be able to access the changes. We have not found a way to do that on the drone server on-the-fly when the starlark code is being execute (which generates the pipelines). We first get "real file access" to the git repo and branch when a pipeline starts. So we were forced to let all the pipelines be generated and start.

We do the calculate-diff early in each pipeline, and at that point we detect if the tests in that pipeline need to be run, or not.

If not, then each step "skips through" and does nothing. And the pipeline exits quickly.

If someone can think of a way to know early enough that a pipeline is not needed, and to not even create the pipeline, then great! Please give your ideas.

**Comment by pascalwengerter** [comment]
Haven't seen this in a while, closing for now
