### ISSUE TITLE
[oCIS] Received share cannot be deleted/unshared if not shared with full permissions

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#5531]
### Steps to reproduce
(using web with oCIS server)
1. as admin, create folder `FOLDER` and share it with user `moss` with `Viewer` role
2. as moss, accept share shared by admin
3. as moss, open `Shares` folder and try to delete the folder `FOLDER`

### Expected behaviour
expected to see delete operation

### Actual behaviour
shared file/folder cannot be deleted if not shared with all permissions (31)
![ocis-share](https://user-images.githubusercontent.com/52366632/125780372-91673c7b-8312-43ac-a59b-3f2509342b89.png)

### Server configuration
oCIS  server built from latest master

**Comment by kulmann** [comment]
For oCIS this will no longer be an issue once we have solved https://github.com/owncloud/web/issues/6448 because the `All files` page (then being renamed to `Personal`) will not contain any shares anymore. Thus the delete action will always be an actual delete operation.

For oc10 I'd love to see that we only show the `Delete` action if it's not a share, and show the `Decline share` action instead when it's a share. I tried that once and it failed horribly in acceptance tests. Would be worth another try though if @tbsbdr agrees.

**Comment by tbsbdr** [comment]
👍 yep agree

**Comment by JammingBen** [comment]
I wanted to dig into this, unfortunately I don't see an easy solution here.

> For oc10 I'd love to see that we only show the Delete action if it's not a share, and show the Decline share action instead when it's a share. I tried that once and it failed horribly in acceptance tests. Would be worth another try though if @tbsbdr agrees.

We somehow need to find out if a resource is the share root (the folder that has been shared itself). There is a method called `isReceivedShare`, but it does not only return `true` for the root of a share, but also for all resources inside a share. `canBeDeleted` on the other hand is always true for share roots in oC10, because it's basically the "Decline Share"-action.

**Comment by JanAckermann** [comment]
@kulmann is this still an issue?

**Comment by kulmann** [comment]
> @kulmann is this still an issue?
> I can decline a share as of today

True, issue has been resolved by switching to the share jail. Thanks for the pointer :-)
