### ISSUE TITLE
remove tests, testing wrong behaviour

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#5595]
### Description
Remove following tests, since they test the wrong behaviour.

```
webUIRenameFiles/renameFiles.feature:129
webUIRenameFiles/renameFiles.feature:128
webUIRenameFolders/renameFolders.feature:118
webUIRenameFolders/renameFolders.feature:117
```
### Related issues
- https://github.com/owncloud/ocis/pull/2334#issuecomment-889826547
- https://github.com/owncloud/ocis/pull/2334/commits/9cc41b9444fb0e8608ff7834e5711dd994afe577

**Comment by phil-davis** [comment]
I can do after https://github.com/owncloud/ocis/pull/2334#issuecomment-889826547 is merged. My plan is that I will update the OCIS commit id in web at the same time, and adjust the tests (or merge them with some other existing scenarios) so that they check that the "rename to name containing a backslash" fails in a "user-friendly" manner.
