### ISSUE TITLE
Feedback on search in 4.0.0

### ISSUE THREAD

**Issue by pmaier1** [owncloud/web#5644]
I have some feedback on the "Search all files" feature which was introduced in 4.0.0. 

When I tried the feature, it felt unexpected because
- ~the left sidebar disappears and the file list becomes full width which felt to me like a bug and~ **not the case anymore**
- I can't easily go back without using browser navigation
- also the behavior is inconsistent with the filtering mode (there the sidebar stays)

I would have expected that 
- when I click on "Search all files", the sidebar stays as it is and the file list shows the results
- when I click the "x" in the search bar ("clear search"), I'm back at the location where I was before searching

**Additional findings**
- When a search query does not have results, it doesn't indicate that. Users can still click on the "suggestion".
- When I'm on the full page results list, the search suggestions don't work. I can can only click on the default "suggestion".

@tbsbdr @kulmann @pascalwengerter

**Comment by rpocklin** [comment]
I agree, with @pmaier1 regarding the left sidebase disappearing (presumably because now it is it's own app, not part of **files**) - this is easily worked around by changing the `sidebarNavItems` function in `App.vue` to set `const items = this.getNavItemsByExtension('files')` instead of `const items = this.getNavItemsByExtension(this.currentExtension)` for the time being.

Also agree with the [x] in the search bar should take you back in the browser history.

Lastly I think a key missing feature is something we implemented previously which is searching sub-folders of the current folder only.  Ie. not a global search, not a current folder search (aka filter) but searching the sub-tree of the current folder - this is the most intuitive search for most people and is really just a global search with a current folder filter after it.

**Comment by rpocklin** [comment]
If there are > 5 items (assuming 5 is the preview search limit) it would be good to show something like ' ... more ...' which is not selectable.  I thought there was a bug since the preview of sdk search didn't show a file in the current folder, but it was just showing the first 5 results (which wasn't obvious, until I looked at the code).

**Comment by pmaier1** [comment]
Added some more findings.

**Comment by tbsbdr** [comment]
**Loadspinner:** Add something like a loadspinner so that users know, that they need to wait.

**Comment by JanAckermann** [comment]
Sum up:

1. Show indicator when the search results exceeds the limit (currently 5)
2. Show indicator if no matches were found 
3. Hit x in search input will go 1 step back in browser history
