### ISSUE TITLE
oc10: Add quick action + context menu "copy private link"

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5695]
## Userstory
> As a user who is used to work with the private link, I want to copy the private as quick as possible.

## Acceptance criteria
- Add private link to quickactions, if capability for private links exists. Add it to the left of the public link quick action (same order as in the right sidebar. private link first, public links last).
- Add private link to context menu, if capability for private links exists. Add it above the `create public link` item (same order as in the right sidebar. private link first, public links last).
- find icons that are visually distinguishable

icons eg:
- https://materialdesignicons.com/icon/shield-link-variant-outline

**Comment by pascalwengerter** [comment]
@tbsbdr why use a different icon than the one from the links section in the right sidebar? There's already a copy-private-link icon/button there

**Comment by tbsbdr** [comment]
Plz help me, i only see those or do you mean sth different?

![Screenshot_20210818-131131.png](https://user-images.githubusercontent.com/26610733/129888383-40d8c3f1-c3de-4cd9-858b-cfc356abc41e.png)

**Comment by pascalwengerter** [comment]
> Plz help me, i only see those or do you mean sth different?
> 
> and jep - If we already have an icon, we'll stick with them.
> 
> ![Screenshot_20210818-131131.png](https://user-images.githubusercontent.com/26610733/129888383-40d8c3f1-c3de-4cd9-858b-cfc356abc41e.png)

Yeah exactly I mean those "Copy link" icons and would vote in favor of re-using them in the contextmenu (from a recognition value POV)

**Comment by tbsbdr** [comment]
ah okay. I didn't write, that i want to keep both links in the quickaction - the public and the private link :-) and therefore I thought the icons should be distinguishable

**Comment by pascalwengerter** [comment]
Then let's add the icon you suggested for private links and use it everywhere the private link appears and needs an icon (for better distinguish-ability)!

**Comment by kulmann** [comment]
Well, the icon is supposed to express three different things:
- it's a link
- it's secure/private
- you can copy it to your clipboard

Pretty hard to find something that expresses all that. ;-) Manually combining the copy icon and the proposed private link item (which I like a lot) into one icon won't look good I'm afraid.

Reusing the generic `copy to clipboard` button from the right sidebar is not an option for the context menu and for the quick action. Because it's generic. ;-)

I'd be fine with using the proposed private link item in the quick action and context menu, but keeping the generic copy icon in the right sidebar, because there we have a lot of context what exactly you're copying.
