### ISSUE TITLE
Can't logout when using keycloak

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#5753]
## Describe the bug

When using oCIS with keycloak, if a user logs out of ocis, they don't log out of keycloak. As a result, they are redirected back to the landing page, which again calls keycloak's `authorization_endpoint`, which logs the user back again.

## Expected behavior
Keycloak exposes an endpoint `end_session_endpoint` which takes a param `redirect_uri`. This should be called when the user logs out of oCIS.

**Comment by wkloucek** [comment]
I transfered this to the Web repo since this needs to be done by the OIDC client => oC Web.

I tried it on https://ocis.ocis-keycloak.latest.owncloud.works/ with oC Web 4.1.0 and looks to work as expected. The full configuration of this deployment can be found here: https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_keycloak.
