### ISSUE TITLE
Notifications queue persists over page navigation

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#5932]
### Steps to reproduce
1. Start oCIS, delete a lot of files (~100 textfiles in my case)
2. Go to trashbin, bulk-restore all files
3. See notifications about successful restore of files persists over page notification and each get displayed for 5s and then removed, showing only the last 5 ones

### Expected behaviour
Page navigation _could_ flush the notifications queue **or** we make them less prominent. Needs a UX decision @tbsbdr 

### Actual behaviour
Refresh of notifications blocks a central point of the UI until all ~100 messages have had their 5s screentime

### Environment ownCloud Infinite Scale
**Where did you install Infinite Scale from:** Binary

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu

**Comment by tbsbdr** [comment]
relates to #7039

**Comment by JanAckermann** [comment]
I am closing this one because of:

* Notifications are now dismissable
* Most parts where notifications have been shown multiple times like "file 1 restored", "file 2 restored" have been merged in to one notification: "2 files restored"


 
![image](https://github.com/owncloud/web/assets/26169327/9210c0ad-3d1c-4d90-8500-b19bd60ee017)
