### ISSUE TITLE
No confirmation dialog for moving files to the trash

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#5974]
## Userstory
_As a user I want to permanently delete files efficiently without having to worry about irreversible damage._ 

## Acceptance Criteria
- **Move to trash:** Don't show a confirmation dialog if a file* gets moved to the trash (reversible action)
  - Show a success notification
- **Empty trash** Show a confirmation dialog if a file* gets deleted permanently (eg. when the bin gets emptied) (irreversible action)
  - Show confirmation dialog: "Empty trash" "Are you sure you want to permanently delete your items in the trash? You can’t undo this action. [Cancel] [Okay]"

More background on:
- https://www.nngroup.com/articles/confirmation-dialog/
- https://docs.microsoft.com/en-us/windows/win32/uxguide/mess-confirm?redirectedfrom=MSDN

\* one or many files or folders

**Comment by pascalwengerter** [comment]
Not sure about the `Show a success message with an undo-option and dismiss-x "XX Item(s) successfully moved to trash. [undo] [X]"` part. IIRC we moved to auto-closing notifications due to A11y reasons, and putting an undo option in there may be a screenreader offense since it doesn't get focus

How about relying on a success message (`Resource X has been moved to the Trashbin`) and the confirmation upon emptying trash/ultimately deleting a single file there? Otherwise I think we need to re-think this ticket again @kulmann ?

**Comment by tbsbdr** [comment]
forgot to mention, that the ~message~ notification should auto-close. added it above. undo would be nice to have, no must-have.
so this means, that we should have no clickable areas in notifications because then we would need to send the focus there and focus management is expensive, correct?

**Comment by JanAckermann** [comment]
> Empty trash Show a confirmation dialog if a file* gets deleted permanently (eg. when the bin gets emptied) (irreversible action)
Show confirmation dialog: "Empty trash" "Are you sure you want to permanently delete your items in the trash? You can’t undo this action. [Cancel] [Okay]"

Will be handled in PR [#6544 ](https://github.com/owncloud/web/pull/6566)

**Comment by kulmann** [comment]
Reopening, because only the confirmation for `empty trash` was done in the linked PR (as being stated in all the messages... ticket was closed accidentally).

**Comment by tbsbdr** [comment]
how about:

- `[filename] was moved to trash bin`
- `2 items were moved to trash bin`
