### ISSUE TITLE
File previews miss authorization header

### ISSUE THREAD

**Issue by diocas** [owncloud/web#6157]
If in a public link I have a file with an extension that is configured in `previewFileExtensions`, the call to get the preview is done without the `authorization` header. This causes the basic auth popup to appear.

Of course this happens if I'm not authenticated to the UI.

**Comment by dschmidt** [comment]
Can you still reproduce this?
Can you give me more detailed information on how to because I currently cannot reproduce this with neither oC10 nor oCIS.

In public link context resources returned by the PROPFIND contain a signed `downloadURL` which is used by oC Web to display the preview, so actually we don't need an Authorization header afaict.

**Comment by diocas** [comment]
I cannot reproduce in your deployment.. Prob some issue in our fork, I'll ask @ishank011 to have a look. Closing
