### ISSUE TITLE
Split ocis pipelines further

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6356]
Looking at https://drone.owncloud.com/owncloud/web/22374 it seems that we can reduce the CI runtime by 4 minutes by splitting the `oCISSharingInternal1` pipeline. It takes 23 minutes, while the longest running pipeline before that takes 19 minutes (`oCISRename`).

**Comment by kulmann** [comment]
@phil-davis could your team take a look?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22372/26/20

oC10SharingFolderAdvPermsGrp also took almost as long.

If we split both then the longest will be around 20 to 21 minutes, better than 24 to 25 minutes.

There are quite a lot of pipelines that take 20, 19, 18 minutes. So reducing those would require creating a lot more pipelines, so we don't do that just yet.

**Comment by kulmann** [comment]
> https://drone.owncloud.com/owncloud/web/22372/26/20
> 
> 
> 
> oC10SharingFolderAdvPermsGrp also took almost as long.
> 
> 
> 
> If we split both then the longest will be around 20 to 21 minutes, better than 24 to 25 minutes.
> 
> 
> 
> There are quite a lot of pipelines that take 20, 19, 18 minutes. So reducing those would require creating a lot more pipelines, so we don't do that just yet.

Full ack. Thank you!

**Comment by phil-davis** [comment]
`oC10SharingFolderAdvPermsGrp` is the suite `webUISharingFolderAdvancedPermissionsGroups`
That has an examples table with various custom permissions combinations, and at the moment all the examples are in expected-failures. They do all fail, and the CI pipeline retries them all.

It would be nice to avoid that sort of silliness - for scenarios that are expected to fail, then running once and failing should be enough! But the nightwatch test runner is not a.ble to know which scenarios are in expected-failures.

For this particular suite/pipeline, we could disable retry, since every scenario is expected to fail. I will think about that...

**Comment by phil-davis** [comment]
> For this particular suite/pipeline, we could disable retry, since every scenario is expected to fail. I will think about that...

I disabled retry for that suite, in PR #6357
