### ISSUE TITLE
Sorting ResourceTable causes lazy loading sceleton to never disappear

### ISSUE THREAD

**Issue by lookacat** [owncloud/web#6434]
### Steps to reproduce
Click sorting at least 3-4 times.

### Expected behaviour
Lazy loading sceleton should not appear

### Actual behaviour
Lazy loading sceleton appears and never goes away

### Screenshot
![sceleton_bug](https://user-images.githubusercontent.com/786551/153889232-0be2a21c-e1b3-4692-bd92-3777e653d345.png)

**Comment by JammingBen** [comment]
@lookacat Could you please check if that's still a thing for you? I suppose that the recent performance updates have solved this issue.

**Comment by JammingBen** [comment]
I had the same issue several times now. It seems to happen when you change the sort order of resources, navigate to another page, and then navigate back to your personal space.

I think it has something to do with reading values from the local storage. Because as soon as you prune it, things are fine again. Also, it only occours when Web is running via `pnpm vite` (for me).

**Comment by kulmann** [comment]
Can confirm. Happens if you navigate e.g. to `Shared with me`, try to sort (which is broken entirely), then navigate back to `Personal`.

Looking at the localStorage (browser dev tools -> Application -> Local Storage) there are view-specific sort key-value pairs. Deleting the view-specific sorting options from localStorage "solves" the issue...

<img width="2757" alt="Screenshot 2023-05-04 at 12 54 15" src="https://user-images.githubusercontent.com/3532843/236188005-f8543adb-808d-4381-8cdd-ecb9de72c84b.png">
<img width="2757" alt="Screenshot 2023-05-04 at 12 54 34" src="https://user-images.githubusercontent.com/3532843/236188024-545e791c-ca0f-49e4-9d2f-c42c7bf587c8.png">

**Comment by kulmann** [comment]
See https://github.com/owncloud/web/issues/8981 for the broken sorting on the shared with me page, that I mentioned in my previous comment.

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/web/pull/8988.
