### ISSUE TITLE
coverage of e2e tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#6521]
see what how it is possible to draw coverage reports when running e2e tests with playwright and make a POC

**Comment by kiranparajuli589** [comment]
The Playwright team has developed a POC for e2e coverage here at https://github.com/mxschmitt/playwright-test-coverage. Overview about it:
- a react based project
- build rewired using https://www.npmjs.com/package/react-app-rewired
- use https://github.com/istanbuljs/babel-plugin-istanbul to collect coverage data during runtime of our e2e tests

I was mostly confused by this babel topic and the idea that how to rewire like they've done with the react, since `web` is built with `vue`. I'd also tried with Class-Coverage feature from the Playwright, but find out the coverage logs to be very big json of just numbers... :( like this:
```json
{"":{"path":"","all":false,"statementMap":{"0":{"start":{"line":1,"column":0},"end":{"line":1,"column":19}},"1":{"start":{"line":2,"column":0},"end":{"line":2,"column":21}},"2":{"start":{"line":3,"column":0},"end":{"line":3,"column":21}},"3":{"start":{"line":4,"column":0},"end":{"line":4,"column":32}},"4":{"start":{"line":5,"column":0},"end":{"line":5,"column":832}},"5":{"start":{"line":6,"column":0},"end":{"line":6,"column":36}},"6":{"start":{"line":7,"column":0},"end":{"line":7,"column":86}},"7":{"start":{"line":8,"column":0},"end":{"line":8,"column":69}},"8":{"start":{"line":9,"column":0},"end":{"line":9,"column":53}},"9":{"start":{"line":10,"column":0},"end":{"line":10,"column":127}},"10":{"start":{"line":11,"column":0},"end":{"line":11,"column":106}},"11":{"start":{"line":12,"column":0},"end":{"line":12,"column":15}},"12":{"start":{"line":13,"column":0},"end":{"line":13,"column":267}},"13":{"start":{"line":14,"column":0},"end":{"line":14,"column":1353}},"14":{"start":{"line":15,"column":0},"end":{"line":15,"column":642}},"15":{"start":{"line":16,"column":0},"end":{"line":16,"column":37}},"16":{"start":{"line":17,"column":0},"end":{"line":17,"column":1695}},"17":{"start":{"line":18,"column":0},"end":{"line":18,"column":97}}},"s":{"0":1,"1":1,"2":1,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1,"9":1,"10":1,"11":1,"12":1,"13":1,"14":1,"15":1,"16":1,"17":1},"branchMap":{"0":{"type":"branch","line":1,"loc":{"start":{"line":1,"column":0},"end":{"line":18,"column":97}},"locations":[{"start":{"line":1,"column":0},"end":{"line":18,"column":97}}]}},"b":{"0":[1]},"fnMap":{},"f":{}}}
```
But there is some tool to view these JSON in better UI. I will try few more hours on this tomorrow. But overall I was not so successful on this. Maybe other perspective would reach us move further than this for the e2e tests coverage.

**Comment by individual-it** [comment]
let's close this for now, because its not a priority
