### ISSUE TITLE
Dynamically expose different space types in the Web UI 

### ISSUE THREAD

**Issue by labkode** [owncloud/web#6649]
Rely on server response to populate spaces view with top level filters like is done for shares:
![Screenshot 2022-03-23 at 11 46 15](https://user-images.githubusercontent.com/5175912/159682484-2c731415-413b-4162-8204-47235a185850.png)

This will remove patches in our fork in our current UI (like HPC, ...)

**Comment by pascalwengerter** [comment]
@tbsbdr needs product decision and concept for a larger amount of driveTypes

**Comment by kulmann** [comment]
Hey, a feature like that is not on our short term roadmap until oCIS GA.

What we can offer in the meantime is that you can have additional nav items for the left side bar. Since those require content like a title or an icon we'll hardcode them in our master and a) decide upon the content of a drive listing whether or not they are shown or b) via build flags. You need that anyway for the eos user space and that's what we agreed upon. This is easily extended to additional left sidebar nav items. See https://github.com/owncloud/web/issues/6648#issuecomment-1077665308 for a timeline for that.

**Comment by tbsbdr** [comment]
realtes to https://github.com/owncloud/web/pull/9159/commits/d5d936c9ca993a187f8d5a9a66c4b838c0e9eb8f

**Comment by kulmann** [comment]
Not planned at the moment. Thanks for sharing the idea!
