### ISSUE TITLE
Buttons "New" and "Upload" are still available after changing the role of the space

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6651]
branch: 5.3.0-rc.3 docker

steps:
- the administrator creates the space
- the administrator gives the space to user1 with the editor role
- user1 can create a file/folder inside the space. The "Create" and "Upload" buttons are available.
- admin changes the role to viewer
- user1 refreshes the page but buttons still available although the answer is that the role of viewer

Expected result: "Create" and "Upload" buttons are not available
actual result: "Create" and "Upload" buttons are available, if user1 tries to create file/folder - get 403

https://user-images.githubusercontent.com/84779829/159697305-bce2b454-b234-46a8-bde8-42dc0c915277.mov

**Comment by JammingBen** [comment]
Thx for reporting! However, this is a backend issue I believe.

At the end, you're checking how the permissions look like in the backend response. But you're checking the wrong request. The right one would be the request where the single drive is fetched (I believe the second one in the list), not the one where all drives are listed.

Ideally, both responses have the same data for this space. But because of a caching issue in the backend this is not the case yet.

**Comment by ScharfViktor** [comment]
Yes, you are right. I'll create issue in ocis
request GET `https://host.docker.internal:9200/graph/v1.0/drives/3ea1ce3d-c34f-4b8e-bc6c-3ffca95e2ae0` give us wrong role after updating role:
<img width="1431" alt="Screenshot 2022-03-23 at 14 15 11" src="https://user-images.githubusercontent.com/84779829/159708242-55461781-6112-4f19-9271-7ee9c894c7fa.png">

request GET `https://host.docker.internal:9200/graph/v1.0/me/drives?%24top=0&%24skip=0&%24orderby=name+asc&%24filter=driveType+eq+project`
<img width="1431" alt="Screenshot 2022-03-23 at 14 15 55" src="https://user-images.githubusercontent.com/84779829/159708599-e9981916-0239-421d-8474-2fc572b93f61.png">

**Comment by ScharfViktor** [comment]
closed in favor of https://github.com/owncloud/ocis/issues/3378
