### ISSUE TITLE
Remove permission check when listing spaces

### ISSUE THREAD

**Issue by ishank011** [owncloud/web#6660]
For spaces with thousands of users via recursive groups, this won't scale

https://github.com/owncloud/web/blob/c2cddef7b391bb26f8a4e9d73ef4288d100a538a/packages/web-app-files/src/helpers/resources.js#L130-L135

This should be delegated to the backend to not return the space if the logged-in user has not been granted permissions to it. The backend still shouldn't return all the users, but rather just the immediate shares. I'll create a separate issue for that.

**Comment by kulmann** [comment]
@JanAckermann or @JammingBen could you take a look if that's possible?

**Comment by JammingBen** [comment]
I don't think it is that easy, unfortunately. We need the permissions to be loaded in the spaces list to properly display context actions (e.g. a viewer does not see the "rename"-action of a space).

I agree that this block isn't optimal in terms of performance, however, it's due to the object structure the Graph API gives us.

> For spaces with thousands of users via recursive groups, this won't scale

Spaces itself cannot be shared with groups, so we won't have such "deep recursive tree" because of that.

 > This should be delegated to the backend to not return the space if the logged-in user has not been granted permissions to it.

Maybe I get this wrong, but IMO this is already the case. A regular user only sees the spaces who they are member of. For those spaces, it is necessary to have the permissions for the reasons stated above.

**Comment by kulmann** [comment]
We need this information because we list the members of a space according to their roles. So this is always needed. While looking at it I found a tiny performance improvement ( https://github.com/owncloud/web/pull/10988 ), but still, we need all the users associated with their respective roles in the response.

**Comment by glpatcern** [comment]
Understood, the issue was opened when we still had hope for a convergent backend, but as we stand now - and with our Spaces in Reva master indeed supporting multiple recursive groups, with cardinalities in excess of 1000s of members - we are anyway feeding the frontend with the minimum information. I'll see with my colleagues how this works.

**Comment by kulmann** [comment]
> Understood, the issue was opened when we still had hope for a convergent backend, but as we stand now - and with our Spaces in Reva master indeed supporting multiple recursive groups, with cardinalities in excess of 1000s of members - we are anyway feeding the frontend with the minimum information. I'll see with my colleagues how this works.

Oh wait, maybe this is partly a misunderstanding. For groups / nested groups this is not an issue. We don't flatten the users from groups or even nested groups into one array here. The permissions list only contains the immediate memberships (users and groups, not user from groups or from nested groups). The group membership info is only loaded and evaluated on the currently logged in user.
