### ISSUE TITLE
Translation issues and inconsistencies in naming of sharing permissions

### ISSUE THREAD

**Issue by Helios07** [owncloud/web#6751]
Hi,

in oc web version 5.3.0 with a language setting of "Deutsch (persönlich)", I see inconsistencies in the naming of the different sharing permissions. Some aren't even properly translated.

### Steps to reproduce
1. Log into oc web
2. Open the sharing dialogue

### Expected behaviour
Consistency. All terms should be in the same language. 

### Actual behaviour
![image002](https://user-images.githubusercontent.com/3447175/162245842-8905a531-0881-456c-a19d-3766d6c6620d.png)
![image003](https://user-images.githubusercontent.com/3447175/162245852-78d52c2f-c9e8-420c-ba67-f25fb298bd07.png)
![image001](https://user-images.githubusercontent.com/3447175/162245778-3a59b382-0443-484e-b02b-55f77214ef17.png)

Best regards,
Holger

**Comment by phil-davis** [comment]
Note: translations are done in Transifex and synced from there. Please check in Transifex. You can add and/or fix translations there and they will end up in the next release.

**Comment by Helios07** [comment]
It doesn't seem to be that easy. I logged into transifex, but cannot create any translations. It asks me to upgrade.

**Comment by pascalwengerter** [comment]
Partly duplicate to #6460 where I pointed out that Transifex doesn't work on `.ts` files as of right now. @Helios07 also please make sure to use current master (the `v5.3.0` release is a couple of weeks old already, better to check the status quo on our updated-after-merge-on-master instance https://ocis.ocis-web.latest.owncloud.works/) since that's where the current translation happens.
For Transifex I bookmarked https://www.transifex.com/owncloud-org/signin/?next=/owncloud-org/owncloud-web/translate/#de, what happens if you access that URL?

**Comment by Helios07** [comment]
Regarding the bookmarked URL, I cannot choose a language (tried two different browsers with extensions disabled)

**Comment by Helios07** [comment]
And I checked at the "latest" instance, translation is not complete there, either.
