### ISSUE TITLE
Pagination works incorrect after changing the number of elements on page 2

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#6768]
branch v5.4.0-rc.4 
web agains ocis docker v 1.19.0

Precondition:
- default pagination. Items per page: 100

Steps:

- Administrator uploads a folder with small files (over 200)
- Go to page "2"
- Change the number of items on the page to 500 or 1000

Expected result:
- Administrator can see all 200+ files on the page

Actual result:
- The page is empty. But If you set up pagination on the first page - works correct

https://user-images.githubusercontent.com/84779829/162714482-e1daa57d-5c8f-4367-be64-784c3c3dd3e6.mov

**Comment by bishwasojha** [comment]
__still getting this issue__

- *probable scenario:* For 1000 images , If `Items per page` is 100, there are 10 pages and,  if `Items per page` is 500 there are 2 pages. Now, if we alter the value of `Items per page` from 100 to 500 on page 3 (or any page other than page 1, 2) we see the error message `No resource found.`. Page 3 won't contain an image because page 1 and 2 can accommodate 1000 images.

[Screencast from 16-11-22 02:33:06 अपराह्न +0545.webm](https://user-images.githubusercontent.com/33860671/202133253-d79147da-6c00-436e-9969-0a7ce3f7b499.webm)
