### ISSUE TITLE
Spaces: Don't provide "New Space" button if user can't create a Space

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7079]
### Steps to reproduce
1. Login to https://ocis.ocis-web.latest.owncloud.works/ as Albert
2. click on "Spaces" > "+New Space" > "Create"
3. Error Message appears "Creating Space failed"

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/26610733/171377406-d4af8165-2866-42f5-ba0c-d3299adf26cb.png">

### Expected behaviour
 - Don't provide "New Space" button if user does not have the permissions to create a Space

### Actual behaviour
- Button is visible and clickable, but always shows a error after "create"

**Comment by kulmann** [comment]
Unfortunately this issue is not as simple as it seems. We don't have any knowledge about backend permissions in the web ui so far. Anything we do so far is related to permissions inherited from shares, which is a completely different story. So we'll have to bring permissions to the web ui first, then we can tackle this task here.
