### ISSUE TITLE
get rid of saucelabs code in drone

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#7186]
do we still need saucelabs? we used to use it for browsers that cannot be run in docker.
If we don't need it we should get rid of the code in `drone.star`

CC @micbar @phil-davis

**Comment by phil-davis** [comment]
drone can easily do Chrome and Firefox. Realistically, the only other browser that we would run automated tests with would be Edge.

That makes the question:

Do we want to run any automated tests with Edge in the "near" future?

**Comment by pascalwengerter** [comment]
> Or if we want to test Chrome / Firefox on Windows or Mac we would need saucelabs or simmilar

We can already easily test against both Chrome and Firefox using playwright/the E2E test suite. I also can't remember a single bug that would've been caught by testing different browsers (ofc it helps that the web dev team seems to be evenly distributed across different popular browsers and that technology has progressed quite a bit since "the old days")
