### ISSUE TITLE
NavigationDuplicated error in console

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7222]
Steps:

- create folder
- go to the folder
- back to personal space.  click "personal" button

https://user-images.githubusercontent.com/84779829/177595186-04b632fc-6072-45c7-8fa3-69dcf279a2e4.mov

**Comment by kulmann** [comment]
We can't avoid it easily at the moment. The reason is that the `Personal` nav item does not include the personal space id. therefore we do a redirect when the personal space url without space id is reached. If you were there before already then it redirects you there again, with one hop in between. Vue router complains about that more than it should. It does no harm to the application.
