### ISSUE TITLE
New Design appears clumsy / too big

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#7333]
## Reproduce

1.  resize your browser window to 1440x680 px
2.  browser and share files

## Problem Description

We received feedback, that the general appearance of the ui is clumsy and/or too big especially on laptop screens.

### Target size is

14'' Laptop Display with ~ **1440 x 680 viewport**

![](https://user-images.githubusercontent.com/26610733/180979161-9f92e71b-bc57-42f3-948a-9f9ec9c0689d.png)

Problem that arise:

*   limited discoverability, reaching buttons or files needs to much scrolling
*   bad aesthetic: too little whitespace

### Expected behaviour

UI must be appealing and useful:

Lets try to adjust those values: 

*   decrease standard font size, ex. 14px
*   decrease button-height, ex. 32 px
*   Increase filelist-scrollable area (don't know how.. ) Dont' decrease filerow-height - this will kill whitespace which is essential!
*   use (embed) appealing font ex. Roboto, Nunito etc.

### Actual behaviour

limited discoverability and aesthetic.

### Comparison

comparison so that we can meet users expectations:

<table><tbody><tr><td>&nbsp;</td><td>Onedrive</td><td>Google Drive</td><td>Box</td><td>Dropbox</td><td>ownCloud Web</td></tr><tr><td>fontsize resourcename</td><td>14px</td><td>13px</td><td>14px</td><td>14px</td><td>16px</td></tr><tr><td>font family</td><td>Segoe UI Web</td><td>Roboto</td><td>Lato</td><td>Atlas Grotesk</td><td>Sans-Serif</td></tr><tr><td>Filerows</td><td>13</td><td>13</td><td>10</td><td>12</td><td>7</td></tr><tr><td>Button-height</td><td>32px</td><td>36px</td><td>32 - 40px</td><td>32px</td><td>40px</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>

### Filerows

and general size-comparisons

![](https://user-images.githubusercontent.com/26610733/180980345-90c5b804-cc58-485f-8c9f-6b306f55d2f8.png)

![](https://user-images.githubusercontent.com/26610733/180979805-98669634-4f03-4431-8efa-4d3667ca8edd.png)

![](https://user-images.githubusercontent.com/26610733/180979908-76681671-09d5-4abc-9aa1-35357400e934.png)

![](https://user-images.githubusercontent.com/26610733/180979984-4071e58a-5fd9-459c-9819-0fb6f5723f4f.png)

![](https://user-images.githubusercontent.com/26610733/180980091-71de26e3-e27d-46db-9de0-072cf4e93873.png)

**Comment by kulmann** [comment]
With https://github.com/owncloud/web/pull/7363 we're switching to:
- default font size 14px (to be precise: 88% of the configured browser font. at the common default of 16px that results in 14px)
- default table row height of 40px (instead of previously 46px)
- default button height results in ca. 35px (instead of 40px from before)
- font face "Inter" has been embedded and is used by default

With those modifications we now fit 12 rows on the viewport size mentioned in the issue description. See screenshot attached. We need to investigate if the row height is too small for typical users. Might go back to something like 42px.

<img width="1447" alt="Screenshot 2022-08-19 at 19 21 10" src="https://user-images.githubusercontent.com/3532843/185674186-440b51d3-3221-4904-8628-8f4899de0317.png">
