### ISSUE TITLE
Misleading wording in shares overview

### ISSUE THREAD

**Issue by dragonchaser** [owncloud/web#7435]
![image](https://user-images.githubusercontent.com/1058116/184108019-016c192b-bfda-4a38-a353-3ff137a76f36.png)

After accepting a share, the "Decline" button stays visible, which is a bit misleading IMHO (Decline signals to me that the share has not been accepted yet). I would prefer a different wording like `Abandon share` or `Leave share`. 

/cc @tbsbdr

**Comment by phil-davis** [comment]
https://www.merriam-webster.com/thesaurus/accept

There are lots of antonyms there for various usages of "accept". "decline" and "reject" seem the more relevant words.
"unaccept" (which is not a proper word) might actually be easier to understand?

**Comment by kulmann** [comment]
I do like `Leave` for accepted shares. 🤔 @pmaier1 @tbsbdr opinions?

**Comment by tbsbdr** [comment]
## Proposal

*   remove "Status" column
*   move the actions "Accept" / "Decline" to the Quickactions-Column for "Pending shares"

## Reasoning

*   I would stick to "Accept" / "Decline" as they are more distinctive antonyms than "Accept" / "Leave" and because its straight forward to click on "Decline" and then find the resource in "Declined Shares"  
*    The "Status" Column is redundant as the status is shown in the headline
*   "Accept" / "Decline" are actions and should move to the Actions column (though I like, that they are next to the resource name 

![](https://user-images.githubusercontent.com/26610733/184590159-3e12331c-e219-4131-aaed-39c8ef40314c.png)

**Comment by dragonchaser** [comment]
@tbsbdr I like the idea of moving the actions into the context menu for accepted shares, but I still do not like the word `decline` to get out of an already accepted share. (but just my 2ct)

**Comment by tbsbdr** [comment]
superseeded by hide/unhide concept: https://github.com/owncloud/web/issues/7551
