### ISSUE TITLE
Sidebar cripples file name which is not visible

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#7471]
When a file has a long file name, it can not be displayed completely in the top of the sidebar.

However, if the sidebar is narrow enough, there is no visible indication that the file name was shortened, as it is in the main view with the dots.

![image](https://user-images.githubusercontent.com/1070214/185112920-793b36bb-7b9f-4103-b9f0-3e242fe57505.png)

A good solution would be to add the ... dots to the filename display.

**Comment by kulmann** [comment]
We decided a few weeks ago that the right sidebar / details section should never truncate the file name. While we implemented that, your reported issue is still valid unfortunately. File names without blanks get cut off at a certain point. Needs to be fixed (ideally by still breaking into the next line)

**Comment by tbsbdr** [comment]
thx for the issue and the oldschool matrix-styled sourcecode :-D

Some refinement of the bug description for the current version of Web:

## Current behavior

![](https://user-images.githubusercontent.com/26610733/185146992-850b1874-f8eb-4682-929f-d238320fcd36.png)

![](https://user-images.githubusercontent.com/26610733/185147108-e8e3d2c8-e9df-4dc7-8bf3-46b92bb46fa6.png)

## Expected behavior

*   resource name: `word-break: break-all`
*   private-Link: `Space should not break`, `align to top`.

![](https://user-images.githubusercontent.com/26610733/185147181-dc98254e-af2b-4001-8efa-533d4387e323.png)

![](https://user-images.githubusercontent.com/26610733/185147326-a7cdda4a-3693-4947-950d-333dca33e628.png)

**Comment by JanAckermann** [comment]
![image](https://user-images.githubusercontent.com/26169327/185223360-4e762f6a-2782-4f6d-bb33-0bec55001430.png)

https://github.com/owncloud/web/compare/issues/7471?expand=1
