### ISSUE TITLE
File preview in shares jail doesn't work due wrong url

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7517]
ownCloud Web UI 5.7.0-rc.10
Infinite Scale 2.0.0-beta.7

Steps: 

- admin shares jpeg file to marie
- marie accepts and click "Show context menu" -> "Details"

Actual: 404 because wrong url: `https://localhost:9200/remote.php/davphoto.jpg?scalingup=0&preview=1&a=1&c=a8b3ea73902cc1d1781611f30c66a415&x=1200&y=1200` instead of `https://localhost:9200/remote.php/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668!d3fb2cf7-2788-4f3c-9d7b-e90642fe463f?scalingup=0&preview=1&a=1&c=a8b3ea73902cc1d1781611f30c66a415&x=1200&y=1200`

![Screenshot 2022-08-24 at 18 04 54](https://user-images.githubusercontent.com/84779829/186468295-6216f120-b5f3-4283-a540-40d9fb7d9128.png)

@kulmann after this error I caught 401 basic auth popups: BUT it doesn't reproduce. 

![Screenshot 2022-08-24 at 18 03 49](https://user-images.githubusercontent.com/84779829/186468300-7db8ba21-239b-4946-937e-36a4657759df.png)

https://user-images.githubusercontent.com/84779829/186468305-b2d7c42f-38ef-4ec0-a558-80b5fee521b4.mov

**Comment by kulmann** [comment]
@ScharfViktor I see two things being wrong:

1. the URL preview is being requested from a remote.php/dav endpoint (which misses a slash, but even with the slash it's wrong). The preview needs to be requested via share jail webdav path, like in the file list. Needs investigation.
2. the 401 doesn't come from the preview, but there is a `GET` request to `https://host.docker.internal:9200/undefined` after the preview request. Needs investigation as well why that happens.


@C0rby in general I have the feeling that malformed requests cause a 401 now instead of a 404 or similar, like before. This leads to the basic auth popups being shown, which is worse than some 404 in the browser console (from a UX perspective). Let's discuss that please 😅
