### ISSUE TITLE
Translations: Context menu items are not translated consistently

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7536]
### Steps to reproduce
1. Right click on a file

### Expected behaviour
Elements are not translated consistently, some items appear in english:

#### German
![grafik](https://user-images.githubusercontent.com/16665512/187180568-140a423d-3485-4a81-9696-ace90f6ab7e1.png)

#### Spanish
![grafik](https://user-images.githubusercontent.com/16665512/187181031-e6ddc360-7254-4ba9-8d28-24ceb953c784.png)

#### Czech
![grafik](https://user-images.githubusercontent.com/16665512/187181183-9758194e-57f5-4f32-b198-22b28d8d4a2b.png)

#### French
![grafik](https://user-images.githubusercontent.com/16665512/187181256-d2e5a9c9-c045-44d0-9f6b-9bc93884a018.png)

#### Galego
![grafik](https://user-images.githubusercontent.com/16665512/187181336-8416d723-aa96-443b-8841-fe1b414d8d80.png)

#### Italian
![grafik](https://user-images.githubusercontent.com/16665512/187181447-9fd313ac-b03b-42bd-823c-8f65bfa05190.png)

ocis & web latest

**Comment by kulmann** [comment]
Two notes:
- `Add or edit tags` needs to be synced to transifex manually because it doesn't live in web master
- translations generally happen via transifex & by community. If something doesn't have a translation in the respective language, we show english as fallback. For german we can (and usually do that) easily take care of translations during the release process. For other languages it's more difficult. If you speak any of the languages I'd be more than happy if you could spend some time on transifex in the project `ownCloud Web`. :-)

**Comment by kulmann** [comment]
@fschade ideas about translations for the experimental branch?

**Comment by hurradieweltgehtunter** [comment]
>  If you speak any of the languages I'd be more than happy if you could spend some time on transifex in the project ownCloud Web. :-)

other than english and german, no. And I never worked with transifex but I'd be happy to contribute

**Comment by mmattel** [comment]
> `Add or edit tags` needs to be synced to transifex manually because it doesn't live in web master

@kulmann have not found that string on tx. Still an issue?

**Comment by kulmann** [comment]
Not an issue anymore. Back then `Add or edit tags` was part of an experimental branch and thus not in sync with transifex. That's not the case anymore as tags are on web master.
