### ISSUE TITLE
Proposal: Add additional file views

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#7564]
Not much to explain, check your favourite OS file explorer.
- Icon view
- List view
- detailed list view
- Column view (check Mac's finder)
- Gallery view

Additionally: A kind of intelligent algorithm could detect which view is most suitable for a folder, e.g. it contains many images? -> gallery view

**Comment by kulmann** [comment]
The scope of this issue is huge. ;-)
There is an issue for a tiles view, see https://github.com/owncloud/web/issues/6126 , which is already actionable and currently planned for after oCIS GA.  For the other views we'll create individual, actionable user stories when they become relevant, but not a priority at the moment. Closing here. Feel free to create a new discussion if you think any of the views is especially important: https://github.com/owncloud/web/discussions
