### ISSUE TITLE
Drive alias: viewing and restoring a file from the works incorrect

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7714]
related to https://github.com/owncloud/web/pull/7430

Steps: 

- Create 2 spaces with the same name "new space" 
- rename one space to "renamed" space
- upload and delete the file from the "renamed" space
- open the "new space" and go to the trash.

Expectation: no file in trash for "new space"

Actual: opened trash bin another space ("renamed" space)
if we delete files from 2 spaces and ope trash bin any space (same alias) -> trash collect all deleted files

https://user-images.githubusercontent.com/84779829/193031834-380cbfdf-e755-41ac-84af-f1dd96d41421.mov

**Comment by kulmann** [comment]
This is a known regression from the drive alias PR. Since duplicate drive aliases are allowed it is not possible at the moment to know which of the spaces to open (applies for the files view and the trash bin of the space). You will only ever see the first space/trash with this drive alias. To fix this we need https://github.com/owncloud/web/issues/6247 (next on my list to implement).
