### ISSUE TITLE
E-Mail address is valid but will be marked as invalid in user view

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#7806]
### Steps to reproduce
1. Create a new user
2. Add a wrong email address
3. Change to valid email address

### Expected behaviour
The e-mail is seen as valid if it's valid immediately (ex. validate upon keystroke)

### Actual behaviour
<img width="388" alt="image" src="https://user-images.githubusercontent.com/33026403/196061600-0bf87ddd-6639-4160-b7fb-34d42b7d67ad.png">

https://user-images.githubusercontent.com/26610733/196124363-f2342246-2b24-4b7e-8ace-ae1894be4e10.mp4

You have to click outside the field to get rid of the message

### Expected behaviour
validation should take place instantly (not only with click-outside of the field.)

### Environment general

**Backend (ownCloud Core or Infinite Scale)**:
oCIS

### Environment ownCloud Infinite Scale
**Version:**
2.0.0 Beta 8
**Updated from an older Infinite Scale or fresh install:**
Fresh

**Comment by tbsbdr** [comment]
Refined initial post, added Video.

thx @ChrisEdS for reporting

**Comment by JanAckermann** [comment]
@tbsbdr  IHMO we had talked about that and you was against the 'on typing validation' because as the user starts to type he would have shown an error message, because not valid. Has this mind changed?

**Comment by kulmann** [comment]
UX is tricky here. We could switch to valid state during typing and to invalid state only on leaving the form field. What do you think?

**Comment by ChrisEdS** [comment]
Make sense.

**Comment by JanAckermann** [comment]
@kulmann agree, on it

**Comment by tbsbdr** [comment]
> @tbsbdr IHMO we had talked about that and you was against the 'on typing validation' because as the user starts to type he would have shown an error message, because not valid. Has this mind changed?

Not 100% sure, but if you ask me I'd recommend the following:

1.  If we are in a `non-invalid state`, 'on typing validation' is bad ux as if gives immediate negative feedback before the user finished her input.
2.  If we are already in an `invalid state`, 'on typing validation' is best as it gives immediate positive feedback if the user has reached a valid state. 'on leaving form validation' is second-best solution in this scenario imo.

Sorry if you already had that in mind and I talked it out wrongly!

Expected behaviour - Example:


https://user-images.githubusercontent.com/26610733/197199772-1cd44235-0753-479b-bbbb-797abe5fe091.mp4
