### ISSUE TITLE
User and group creation improvements

### ISSUE THREAD

**Issue by enbrnz** [owncloud/web#7937]
### Steps to reproduce
1. Go to user management
2. Create new user or group
3. Fill out details
4. Hit ENTER

### Expected behaviour
User or group should be created

### Actual behaviour
- During user creation, nothing
- During group creation, page is reloaded without creating specified group

### Environment general
**Operating system**:Linux

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** ocis single binary (no docker)

### Environment ownCloud Infinite Scale
**Version:** 2.0.0-rc.1

**Updated from an older Infinite Scale or fresh install:** fresh install

**Where did you install Infinite Scale from:** github

### Client configuration
**Browser:** Firefox 106.0.4 snap for Ubuntu

**Operating system:** Ubuntu 22.04.01 LTS

**Comment by JanAckermann** [comment]
@enbrnz 
This is weird, what you are describing is not an improvement request, but a bug!
Users and groups should be displayed in the respective table after creation.

Could you share your console output with us?

**Comment by kulmann** [comment]
@JanAckermann I think the issue here is that when you press `Enter` on your keyboard while being in the form, the behaviour described above can be observerd. The `Enter via keyboard` was missing in step `4`.

I agree, we should trigger the submit button for both forms upon pressing `Enter` on the keyboard if that's easily possible.

**Comment by JanAckermann** [comment]
LOL, ok sure will take care (:
