### ISSUE TITLE
Make "Add Link" a button (like we have with Share)

### ISSUE THREAD

**Issue by mmattel** [owncloud/web#7939]
@kulmann fyi

Taking the ocis.team instance, there is a possible improvement for the UI to make the experience more streamlined.

The **Add link** text on the lower left should be in the same style and location (lower right) as we have it with the **Share** button.

**Tweaked image**

<img src="https://user-images.githubusercontent.com/3321281/200586878-253c9dff-9869-4ad8-bbec-7aa1775f6e33.png" width="300">

**Comment by kulmann** [comment]
No, that's not the button to submit the form above. It's an action to add another link. That's why we decided to change the link name to `Add another link` in https://github.com/owncloud/web/issues/7891
Closing here. Please reopen if I missed something that's not covered by https://github.com/owncloud/web/issues/7891

**Comment by mmattel** [comment]
I am not complaining about the text like `Add another link` or say that the button is submitting the form above. The forms are clearly separated and independent. I say that from a user perspective, having one time a button on the right and one time a text on the left is inconsistent and confusing.

**Comment by kulmann** [comment]
In my opinion it would be **misleading** to have two buttons aligned to the right. Because it would give the impression of having two forms, working in similar ways, with their respective submit buttons. That's not the case.
