### ISSUE TITLE
[Bug] Don't see share receivers for my spaces in "Shared with others" view

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#8124]
### Steps to reproduce
1. Create a space, share with another user and create a link share for it
2. Share seems to be auto-accepted?
3. Head to `Shared with others` and `Shared via link` and only see the shared space on the Share-Link page
    Bonus: The other user sees all the links and can copy/share them, even if he only has view rights (see screenshot below)

### Expected behaviour
Maybe that's intended, but I just confused because I can see shared spaces in the `Shared via link` view, while I can't see the same space in `Shared with others` even though I've added both links and people

### Actual behaviour
Unclear

<img width="464" alt="Screenshot 2022-12-15 at 19 29 53" src="https://user-images.githubusercontent.com/16822008/207938394-ad83b561-d269-47e2-8445-3145c19f8f82.png">

**Comment by JammingBen** [comment]
I think this needs a decision by @tbsbdr .

Currently, it is expected behaviour because space members are not like traditional shares. In a traditional share, you have "`User A` shares file with `User B`". Then `User A` sees the file on their `Shared with others page`. With spaces though, we don't have the information who has been invited by who AFAIK.  All space admins can invite other users as members. So it would raise the question: Who should see the space on their `Shared with others page` page? All space members? Only space admins? Nobody?

Personally, I don't think we should include spaces on the `Shared with others` page. But I get the confusion... Maybe we need to make the difference between shares <> space members more clear in the UI 🤔

**Comment by tbsbdr** [comment]
yahh, I get your point, but I'd stick to the current solution as **shares != Members** as @JammingBen pointed out.
