### ISSUE TITLE
Universal "app context" top bar

### ISSUE THREAD

**Issue by dragotin** [owncloud/web#8422]
when opening a file in a viewer or editor in ownCloud web, it should display an area in the top bar that shows the file name, a "three dot" menu offering actions of the editor, and possibly a close button that closes the editor.

The idea is to integrate that into the topmost darkblue bar of oC Web to not waste vertical space for that.

CERN has a prototype implementation that should be integrated into the product.

@tbsbdr @diocas @elizavetaRa

**Comment by diocas** [comment]
This is our prototype: https://github.com/cernbox/web/commit/2f1d8a40288270b1c41695ccd8f4bbbd87e90df5

In practice, we don't use it (we have a not so pretty workaround) because we didn't have a way to import some missing components (like the context actions), into our own external applications.

**Comment by tbsbdr** [comment]
Design polishing proposal
- less dominant
- no "Tab" mimic, because it is not a tab (no toggle with other tabs possible)
- more aligned with the users visual memory

any objections?

## Current
![image](https://user-images.githubusercontent.com/26610733/218865895-56689986-f2ef-469d-830b-8cb77aac5398.png)

## Proposal
![image](https://user-images.githubusercontent.com/26610733/218865543-29c3c0f4-5bb1-4163-886b-98f109ad98c9.png)

## Users visual memory shaped by
![image](https://user-images.githubusercontent.com/26610733/218866940-27d03f80-48bb-4e62-9281-faab2bc62943.png)

**Comment by diocas** [comment]
I like it, but maybe it's too understated? Could we put a very light background around it? (not necessarily looking like a browser tab, but nowadays tabs have different visual styles, so I'm not sure what we can do to avoid it)

**Comment by elizavetaRa** [comment]
@tbsbdr I suggest the configurable app context bar background, you can leave it unset, we'd like to have it a little different from the background color. We'll try to implement towards this idea.
Also configurable setting for file icon as a suggestion. We reuse oc-resource where it's given by default
![Screenshot from 2023-02-15 16-24-46](https://user-images.githubusercontent.com/7430156/219072290-ddfd8150-5459-4af8-b731-bbb315db6c59.png)

**Comment by tbsbdr** [comment]
- jup, configurable background is a good idea 👍
- if the configurable app-icon is < 60 mins effort I'd go with it @pascalwengerter

Default impression for the product should be a discreet top-bar, i.e. default: no tab-style, no icon.
