### ISSUE TITLE
Password field can't be empty message

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/web#8521]
### Steps to reproduce
1. Create a public link
2. Add a password
3. Type in a password

### Expected behaviour
`Password field can't be empty` message disappears when a password is set (when I start typing a password) 

### Actual behaviour
`Password field can't be empty` stays forever

<img width="512" alt="image" src="https://user-images.githubusercontent.com/33026403/222238848-db29df81-eba6-4492-8930-54983869622b.png">

**Comment by kulmann** [comment]
In order to make this issue actionable:
- for consistency with all other modals we should not show the empty password warning/error initially when the modal opens.
- the error message should be red (= error message style)
- like stated in the issue description the error message should go away as soon as the input fields holds at least one character
