### ISSUE TITLE
[admin-settings] "Unsaved changes" shown without doing any changes

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8548]
### Steps to reproduce
1. Go to admin settings
2. Click on pen icon ("edit user") in table row (**not** right click -> edit)
3. Right sidebar opens

### Expected behaviour
No hint or "No changes" is displayed.

### Actual behaviour
Hint "Unsaved changes" is displayed.

The described behaviour seems not to be consistent. I tried different click paths and sometimes the behaviour changes ("No changes" is displayed). It also differs for example if I right click on user -> edit -> or right click -> details -> edit user --> "No changes" is displayed.

Another action when this happens (sometimes):
1. Go to admin settings
2. Click on pen icon in table row (not right click -> edit)
3. Right sidebar opens
4. add or remove a group to the user
5. Click "save"
6. Click on another user
7. "Unsaved changes" is displayed.

### Environment general
https://ocis.ocis-wopi.latest.owncloud.works

ownCloud Infinite Scale
Version: 2.0.0+2bf458385
Web-Client Version: 7.0.0-rc.16

**Comment by JammingBen** [comment]
Phew, good find!

Some technical background, whoever tackles this issue: We load additional data when selecting (=clicking) a user. I assume that sometimes this data is being loaded when the sidebar panel is displayed (good), and sometimes it's not yet loaded (bad). In that case we need to implement a proper loading state.

This also explains why this issue is not happening via context menu -> edit: there is enough time to fully load the additional data when going that route.
