### ISSUE TITLE
[spaces] Remove member is labelled as "Remove share" (Rename)

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8670]
### Steps to reproduce
1. Go to Files → Spaces
2. Edit space members
3. Click on three dots menu of removable space member.

### Expected behavior
Action is somehow context based, like “Remove space member” or “Revoke Access”
Also, the following modal shows context-based texts:
Title: Remove Member <username>
Body: Are you sure you want to remove this member | user | group?

### Actual behaviour
The action is called “Remove share”
Further, the following Modal reads 
Title: Remove share
Body: Are you sure you want to remove this share?

I know, the underlying concept is a share, but the user doesn't know that. The user flow is “Remove a person/group from a space” and IMO the presented texts should represent that.

I could imagine that this is also an accessibility issue.

### Environment general
ocis.ocis-wopi.latest.owncloud.works

**Comment by kulmann** [comment]
Let's go with `Remove member` for the context menu item

**Comment by pascalwengerter** [comment]
I've taken a very quick look, it's not quite as trivial since [the actual dropdown](https://github.com/owncloud/web/blob/2ef7df6144256c4dfb082d9fdcac37801a6e81eb/packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue) featuring the "wrong" string gets re-used also in the user's personal space, for individual shares, where `member` might be overblown as well.

The changes to the individual modals ([e.g. the space modal](https://github.com/owncloud/web/blob/2ef7df6144256c4dfb082d9fdcac37801a6e81eb/packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue)) should be fine.
