### ISSUE TITLE
[share-dialog-redesign] IV: Permission "Internal"

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8752]
This is a sub-task of https://github.com/owncloud/web/issues/8743

While screening all available permission when sharing resources, I stumbled upon the permission “Internal” (Sharing via link).

I cannot get my head wrapped this “permission”. As far as I understand, this is a link to a resource within ownCloud which requires the user to be logged in, like the private link in oc10?
It seems to me that this is misplaced in the “permissions” section when sharing because technically it's not a permission but a requirement. While the other permissions, for example “Editor”, grants the user the right to edit a resource, the “permission” “internal” does not grant anything but **requires** the user to be logged in. Therefore, it says nothing about what the user is allowed to do → Not a permission.

Please correct me, if I misunderstood this.
But If I'm not mistaken, the “Internal” should not be listed in the permissions.

Proposals:
- Add it to sharing links as optional option “[ ] Requires login” (not sure if it makes sense to share a resource via link with internal users... ? )
- If it is the private link from oc10 add it—parallel to the quick link—as separate link type.

**Comment by kulmann** [comment]
Your understanding of the `Internal` link role is correct. We already had the realization that it is misplaced in the links section. It only serves as a kind of "pointer" for the people that have access via a share or a space membership.

The underlying idea was, that we don't want to confront the user with multiple types of links (private vs public link) anymore, because that's also hard to grasp as a concept. oCIS doesn't show multiple link types anymore, only a `link`, which has the `/s/<linkToken>` URL syntax, independent from the role. But it turned out that the internal role is hard to grasp in a similar way to the private link.

**Comment by hurradieweltgehtunter** [comment]
Thanks for the info!
Please have a look at: https://github.com/owncloud/web/issues/8750 -> Quicklink

Can't this be combined? Quicklink is the internal pointer. end of story. 
If you need links with permissions, create one.
?

**Comment by kulmann** [comment]
Share dialog redesign is not on the roadmap. What we currently have works for now. Thanks for the input, maybe later when we come back to this in the future.
