### ISSUE TITLE
[files-app] Sharing: Link creation fails

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8899]
### Steps to reproduce
1. Login with user, role "student" (should be able to create sharing links, at least "internal")
2. Open sharing menu of resource
3. Click on "Create link"

OR 

4. Click on Quicklink icon / Create quicklink

### Expected behaviour
Link gets created, fallback to internal link if other permissions are not available

### Actual behaviour
Nothing happens, request has status 200, content:
```
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>104</statuscode><message>user is not allowed to create a public link</message></meta></ocs>
```

**Comment by kulmann** [comment]
I see two different issues, one backend issue (your step 3), one web-ui issue (your step 4):

Creating a quicklink as a student results in a ui error:
```
vendor-eccddd70.mjs:1 TypeError: Cannot read properties of undefined (reading 'name')
    at Proxy.isPasswordEnforcedFor (web-app-files-2160c6f4.mjs:9:21771)
    at Proxy.checkLinkToCreate (web-app-files-2160c6f4.mjs:9:22158)
    at Zs (vendor-eccddd70.mjs:1:26104)
    at Dn (vendor-eccddd70.mjs:1:26183)
    at Dne (vendor-eccddd70.mjs:1:28603)
    at createQuickLink (web-app-files-2160c6f4.mjs:9:17088)
    at Zs (vendor-eccddd70.mjs:1:26104)
    at Dn (vendor-eccddd70.mjs:1:26183)
    at Dne (vendor-eccddd70.mjs:1:28603)
    at Proxy.$_ocButton_onClick (index.html-d3964db0.mjs:5:25802)
E
```

Needs to be debugged and fixed in web.

However, the link (not quicklink!) creation payload looks correct, i.e. this is a backend issue:
```
shareType: 3
path: /New folder
space_ref: 0dd2c554-61ce-4c46-bceb-1962ce93fac3$1177c0b3-6c78-4209-b073-0fdf40ec4422!e1ed2b2d-5fb6-40d1-8ab3-b0d2e3b34102
permissions: 0
name: Link
```
-> the web ui is correctly setting `permissions: 0` and `shareType: 3` in the link creation request. That is tracked here: https://github.com/owncloud/ocis/issues/6036
