### ISSUE TITLE
keyboard navigation -> click checkbox, press shift, click an underlying checkbox -> not all selected 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/web#8989]
@lookacat we've already spoken about that:

If I click a checkbox, press shift, and click the checkbox at the end of the list, not all items in between get selected 

![image](https://user-images.githubusercontent.com/26169327/236483279-7c31d69e-631b-497b-977b-5b0c9db85242.png)

**Comment by kulmann** [comment]
The linked PR fixes the issue but unfortunately opens up a new one.

## Steps to reproduce:
1. Have a folder with e.g. 4 files/folders
2. Click on the first one
3. Hold SHIFT and click the checkbox (!) of the last row

## Expected behaviour
The range of files/folders gets selected AND since all items in the list have been selected the `Select all` checkbox in the table header also gets checked.

## Actual behaviour
Actually two glitches:
1. The `Select all` checkbox in the table header doesn't get checked
2. If you deselect one of the items again via click on the checkbox, the `Select all` checkbox gets checked (indicating that all items are selected) although one item is now deselected.
