### ISSUE TITLE
All resources from various spaces are downloaded into a single parent folder"

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#9164]
### Steps to reproduce
1. Create multiple space `Space1` , `Space2`, `Space3`
2. make the content of `readme.md` different for all 3 space so we know which differentiate after the download
3. create folders `Space1` and `Space1/S1` in project `space1` and one file `makefile.md`
4. create folders `Space2` and `Space2/S2` in project `space2` and one file `zip-extension.md`
5. create folders `Space3` and `Space3/S3` in project `space3` and one file `c_programming.doc`
6. download all 3 spaces using batch action 
![Screenshot from 2023-06-06 14-47-03](https://github.com/owncloud/web/assets/54478846/3e10f0eb-0f82-4e8b-81a1-a30bbadf5eb4)

7. All resources from different spaces are consolidated and placed together in a single folder during the download process.
8. .space contain only one `readme.md` ✖️ 
![Screenshot from 2023-06-06 15-02-03](https://github.com/owncloud/web/assets/54478846/523b617c-181c-4381-b62b-b71d71a6190c)

### Expected behaviour

The resources should be organized and categorized based on their respective projects within the downloads folder.

### Actual behaviour
The download includes resources from all spaces combined into a single folder.

### Environment general
![Screenshot from 2023-06-07 17-30-37](https://github.com/owncloud/web/assets/54478846/1642a2b4-1232-4bc9-aff3-63a4cae371f1)

**Operating system**: ubuntu22.04

**Backend (ownCloud Core or Infinite Scale)**: ocis

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Environment ownCloud Infinite Scale
**Version:** latest
 
**Updated from an older Infinite Scale or fresh install:** fresh

**Where did you install Infinite Scale from:** github

**Comment by ScharfViktor** [comment]
Yes, I can confirm. and we lost data if we have same file name in two spaces

- create: `space1/test.txt` with content `from the space 1` and `space2/test.txt` with content `from the space 2`
- download space1 and space2 

Actual: 
<img width="667" alt="Screenshot 2023-06-07 at 14 11 06" src="https://github.com/owncloud/web/assets/84779829/ccc3b9eb-9955-444a-8ef5-a2b53d883411">

**Comment by JanAckermann** [comment]
I am not quite sure that it's expected to download spaces in a batch action in general.

@tbsbdr @kulmann whats your opinoin?

**Comment by kulmann** [comment]
Downloading multiple spaces via batch action happened accidentally. We only want to offer it for single spaces. Reasoning:
- the archiver service in ocis/reva has an archive size limit. that is already easily reached with single spaces. For multiple selected spaces I would assume that a user reaches the archive size limit quite easily if not even all the time. That usability of this has a high risk of being frustrating.
- downloading multiple spaces probably is some kind of backup scenario. This should be achieved differently.

This issue should be fixed by changing the product to only allow the archive download for single spaces, not as a batch action.
