### ISSUE TITLE
Uploading the same folder twice in parallel shows unexpected behavior

### ISSUE THREAD

**Issue by rhafer** [owncloud/web#9220]
When trying to upload the same folder in parallel twice using the WebUI. The second upload will somehow fail when creating the initial folder (the initial MKCOL seems to fail) but  the it will start uploading the subfolder of  the uploaded directory into the top level folder. See the attached screen recording for details (the first upload finished around 1min into the video)

https://github.com/owncloud/web/assets/373399/55784aed-0522-4287-8e9c-e7c2334b0f30

This looks pretty much like an issue in web to me. Looking at the dev console I could see the MKCOL on the top-level folder  (`kubespray`)  failing (which I guess is ok since it already exists), but that it does an MKCOL on the toplevel for one of subfolders of to be uploaded folder (`.git` in this case).

**Comment by jacob-nv** [comment]
@JammingBen  I was able to replicate it about once and partially. I never really see other upload displayed in progress bar. Fail message never displayed for me. Subsequent uploads of same directory were just blocked.

The one time I was able to replicate it was some combination of network throttling to trigger that. Strangely the uppy service sends path to file without source directory. But wasn't able to recreate it once again since to investigate more.
