### ISSUE TITLE
Backups App

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9267]
- relates to: https://github.com/owncloud/web/pull/9159/commits/27146023f4ca5793a16e16382b353aaf67bb37d4
- enable to run the app as extension
- provide an option to reuse components

**Comment by kulmann** [comment]
We discussed in a call that ownCloud will not implement the `Backups` app, but will provide component reusability as needed. @labkode @diocas @elizavetaRa please confirm.

@elizavetaRa @diocas please provide a full list of components and composables from the files app that are needed in a more generic way (= web-pkg).

**Comment by labkode** [comment]
Hi @kulman,

The list of components are available as `imports` in the following commit:
https://github.com/cernbox/web/commit/27146023f4ca5793a16e16382b353aaf67bb37d4

**Comment by pascalwengerter** [comment]
> Hi @kulman,
> 
> The list of components are available as `imports` in the following commit: [cernbox@2714602](https://github.com/cernbox/web/commit/27146023f4ca5793a16e16382b353aaf67bb37d4)

Just want to point out that this goes beyond the scope of "just four components imported" since
- it imports helpers, composables and more (search for `'web-app-files/` within `packages/web-app-backups/src/components/BackupsSection.vue`
- `AppBar` and `ResourceTable` both use further helpers/composables/components from the files app and interact with the store, which needs to be taken into consideration when estimating the complexity behind an extraction.

Not saying it's not possible though, I suppose an extension system would actually greatly benefit from having these available

**Comment by labkode** [comment]
@pascalwengerter in case it helps: https://github.com/owncloud/core/issues/17610

**Comment by pascalwengerter** [comment]
> @pascalwengerter in case it helps: [owncloud/core#17610](https://github.com/owncloud/core/issues/17610)

Are you sure the link you provided is the right one? It doesn't fit to how the current project is set up or a modern approach to JS. What we will have to do to resolve #8281 (and thereby this issue) is to extract the used functionality into e.g. the `web-pkg` submodule and therefore make it available to extension developers
