### ISSUE TITLE
File Control Bar overlaps Logo

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9608]
### Steps to reproduce
1. Upload this logo 
(https://github.com/owncloud/web/assets/26610733/fd36c3bd-6b76-4131-87d8-f78e99530f8c)
2. open a txt file
3. File Control Bar overlaps Logo

![screenshot_001575](https://github.com/owncloud/web/assets/26610733/bccd8c86-938e-4d2b-bb65-9e349b01da46)

### Expected behaviour
- File control bar should be next to logo, not overlaping

### Actual behaviour
- File Control Bar overlaps Logo

**Comment by tbsbdr** [comment]
Note: If that helps we can set a max-width of something like 190px (= 1:5 ratio at 38px max-heigth)
cc @lookacat

**Comment by jacob-nv** [comment]
Working on it

**Comment by jacob-nv** [comment]
@JammingBen 

I have looked through the CSS. The issue is that the first column has a static width of 150px (which is fine for the default logo), with the wider logo you'll get this overlap. 

One solution would be to increase this size, but this would create a wider gap between the logo and the save file component.
![image](https://github.com/owncloud/web/assets/138569835/2ae3514b-b7c0-4e17-90a9-842e0fb476d4)
![image](https://github.com/owncloud/web/assets/138569835/2a57282a-e871-4397-ae2e-b3c3ca3e6fd5)



A better solution would be to remove static width and split it evenly into 3 columns, where the save file component would be centred. 
![image](https://github.com/owncloud/web/assets/138569835/71a98d27-20c3-43a4-8961-469ab4f83a1c)

**Comment by JammingBen** [comment]
> A better solution would be to remove static width and split it evenly into 3 columns, where the save file component would be centred.

We had the file control bar centered before but decided against this - it should really come after the logo. Do you see any other solution to achieve this without increasing the size of the first column? A dynamic solution would be ideal here, but I don't know if we can achieve such with the existing column-layout.

**Comment by tbsbdr** [comment]
cc @hodyroff
