### ISSUE TITLE
spaces at the end and the beginning of a filename are trimmed away for display

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#964]
### Steps to reproduce
1. have a files called `   my file.txt    ` (spaces at the beginning and the end of the name)

### Expected behaviour
spaces are displayed in the UI

### Actual behaviour
spaces are trimmed 

![image](https://user-images.githubusercontent.com/2425577/56110575-bdff9700-5f74-11e9-9ec7-6a07db76e989.png)

`file-name` attribute in `a class="oc-file file-row-name"` has the correct name but the content of `<span class="oc-file-name">` has the trimmed name

![image](https://user-images.githubusercontent.com/2425577/56110631-eab3ae80-5f74-11e9-85db-61daf12c4432.png)

corresponding issue in core: https://github.com/owncloud/core/issues/35017

**Comment by paurakhsharma** [comment]
@DeepDiver1975 What is the expected behavior here?
The name of the file in devtools seems to contain space. But the webUI doesn't show the space.
We can access the file with space using the API 
`curl http://admin:admin@localhost/remote.php/dav/files/admin/%20newFolder --request PROPFIND`

Is there any benefit of being able to name a file/folder with spaces at the beginning or the end?
It will make the user confused having two folders with the same name.
Why don't we trim the name when the user tries to create a file/folder with space?

**Comment by PVince81** [comment]
I think we likely also did not display spaces in the old UI.

Here in Phoenix I noticed that we forbid trailing spaces when creating files and folders, so this ticket would mostly be about how to handle such entries that already existed.

If we do want to display the space, should it maybe be displayed in red then ?

**Comment by LukasHirt** [comment]
> we forbid trailing spaces when creating files and folders

This was done due to the issue that the items got renamed into completely different names. So even if we decide to allow them - we'll need to investigate what causes that issue https://github.com/owncloud/smb_acl_frontend/issues/82

**Comment by kulmann** [comment]
This has been solved. See following screenshot:
<img width="203" alt="Screenshot 2021-09-09 at 22 23 56" src="https://user-images.githubusercontent.com/3532843/132757452-c1396fa3-9d8c-4104-9f7f-d1fb7cab5970.png">
