### ISSUE TITLE
Private link does not open in default app

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9799]
### Steps to reproduce
1. Create `for-Albert.docx` and create a private link "Only invite ppl can view"
2. send the link via email to albert
3. Albert accepts the share
4. Albert clicks on the link in the email
5. Private Link does not open in default app

### Expected behaviour
- The private link should open in the default app (eg. Collabora - same behaviour as for public links)

### Actual behaviour
- Private Link does not open in default app

**Comment by tbsbdr** [comment]
Labeling as bug as enduser experienced it as "broken". debatable, but I decided to take the enduser perspective. (also shows that the public link experience is quite well received)

**Comment by tbsbdr** [comment]
@JammingBen wondering if there will occur any unwanted sideeffects if we change the behaviour of the private link to the behaviour of the public link. seeing the file-tree (location of the shared file) will still be possible if you select X-Close in the file control bar. so that should still work out...

**Comment by JammingBen** [comment]
@tbsbdr Turns out this is a bit messy as it is currently... Internal and public links behave differently when it comes to opening files. When solving this issue, private links will resolve into the default app, whereas public links resolve into the file list and highlight the file. Should we align this and always resolve into the default app?
